### ISSUE TITLE
LOG TIME WITH FIRMWARE "RTK_SURVEYOR_FIRMWARE_V1_11"

### ISSUE THREAD

**Issue by IngridBerru** [sparkfun/SparkFun_RTK_Firmware#105]
Hello,
I updated the firmware of the Sparkfun RTK Express +(Rovers) and Sparkfun RTK Surveyor (Base) and I have a question regarding the Max Log Time and the Max log length:
* I understood that with the new firmware we can have many logs of 2880 minutes as the SD Card allows it. In our project, we need to have a continuous measurement of a position for at least a month, so with this upgraded firmware version Can we obtain that measurement for that period of time, or are we still restricted to the 2880 minutes and then logging will cease?
* We have an SD card (32GB) do you know if a 32Gb store will be enough to measure the desired period of time?
* If we were restricted, Would you have a recommendation or a tutorial to change this configuration and allows us to measure for a longer period of time?

Thank you so much in advance for your help.

**Comment by nseidle** [comment]
> Can we obtain that measurement for that period of time, or are we still restricted to the 2880 minutes and then logging will cease?

Set your 'max logging time' to 43,000 or more (60 min * 24 hours * 30 days = 43,200), then set your 'max log length' to 24 hours. This will create 1 log for each day and stop logging on the 30th day. After the deployment, the individual logs can be downloaded from the SD card and spliced together to create your larger, single, month long dataset.

> We have an SD card (32GB) do you know if a 32Gb store will be enough to measure the desired period of time?

To determine your data generation rate, attach your device to a computer, open up the terminal and view the output of your unit.

![image](https://user-images.githubusercontent.com/117102/166812366-365d281b-cfc9-4b84-b6c9-13a5d1fdb3b1.png)

Above, my unit has NMEA+RAWX+SFRBX messages enabled (the standard '7'). The log is increasing ~12kB/s. It varies as SIV changes. That's 0.012MB * 60 seconds * 60 minutes * 24 hours = 1,036MB or 1GB per day. Your card will theoretically last around 32 days but these are all very rough estimates. 

Data generation rate depends on the number of messages you are trying to log. Do you have RAWX and SFRBX messages turned on? At what frequency? The ZED-F9P has the ability to output over 50 different messages, and if you set the fix frequency to something very high (>4Hz) and enable some of the larger messages you can generate MBs per second. 

> If we were restricted, Would you have a recommendation or a tutorial to change this configuration and allows us to measure for a longer period of time?

Sure, that's what this place (the repo issues) is for. Please recommend a feature or change you'd like to see and we'll consider it.

FYI - v1.11 of the firmware had a small bug that caused Bluetooth connectivity to fail if the unit was factory reset. There's a few ways to fix it, but the real fix is to move to v1.12.
