### ISSUE TITLE
Memory Loss: Rover Fix -> WiFi Config -> Rover Fix

### ISSUE THREAD

**Issue by LeeLeahy2** [sparkfun/SparkFun_RTK_Firmware#122]
### Subject of the issue
Free heap space is reduced by over 20K bytes when transitioning the system from Rover Fix -> WiFi Config -> Rover Fix.

### Your workbench
* What version of RTK Surveyor firmware are you running?   main (6126b9151fb518471f35d9e838dd433a61b5f03c)
* Are you connected to the device over Bluetooth? What app?   No
* Are you transmitting NTRIP back to the device?   No
* How is everything being powered?   Battery / USB cable
* Are there any additional details that may help us help you?

### Steps to reproduce
On an RTK Express:

1. Power on the RTK Express in Rover mode
2. Enter serial config
3. Select the system menu
4. Select the debug menu
5. Enable heap debug
6. Exit the Serial config mode
7. Allow the RTK Express to get a fix
8. Press and release the setup button to enter Setup mode
9. Press and release the setup button until WiFi Config mode is selected
10. Allow the RTK Express enter WiFi Config mode
11. Press and release the setup button to enter Setup mode
12. Press and release the setup button one or more times to select Rover mode
13. Allow the RTK Express to get  fix in Rover mode

### Expected behavior
The free space in the heap should be with a few bytes compared to the previous RTK Express mode value.

### Actual behavior
The free space in the heap is reduced by over 20K.  See the beginning of the log below.  The initial state is Rover - Fix.  The log shows the initial free space size, the free space range, the final free space value and the next state.

`    |
    |  Free Heap bytes
    |  79868
    |  79776 <= bytes <= 79868
    |  79776
    V
Display Setup
    |
    |  Free Heap bytes
    |  79776
    V
WiFi Config Not Started
    |
    |  Free Heap bytes
    |  79776
    |  79776 <= bytes <= 166924
    |  166924
    V
WiFi Config
    |
    |  Free Heap bytes
    |  166924
    |  75060 <= bytes <= 166924
    |  75060
    V
Display Setup
    |
    |  Free Heap bytes
    |  75060
    V
WiFi Config Not Started
    |
    |  Free Heap bytes
    |  75060
    V
WiFi Config
    |
    |  Free Heap bytes
    |  75060
    |  72452 <= bytes <= 75060
    |  72452
    V
Display Setup
    |
    |  Free Heap bytes
    |  72452
    V
WiFi Config Not Started
    |
    |  Free Heap bytes
    |  72452
    V
WiFi Config
    |
    |  Free Heap bytes
    |  72452
    |  69844 <= bytes <= 72452
    |  69844
    V
Display Setup
    |
    |  Free Heap bytes
    |  69844
    V
Rover - Not Started
    |
    |  Free Heap bytes
    |  69844
    |  69844 <= bytes <= 134388
    |  134388
    V
Rover - No Fix
    |
    |  Free Heap bytes
    |  134388
    |  37528 <= bytes <= 134388
    |  37528
    V
Rover - Fix
    |
    |  Free Heap bytes
    |  37528
    V
Display Setup
    |
    |  Free Heap bytes
    |  37528
    V
WiFi Config Not Started
    |
    |  Free Heap bytes
    |  37528
    |  37528 <= bytes <= 124700
    |  124700
    V
WiFi Config
    |
    |  Free Heap bytes
    |  124700
    |  67112 <= bytes <= 124700
    |  67112
    V
Display Setup
    |
    |  Free Heap bytes
    |  67112
    V
WiFi Config Not Started
    |
    |  Free Heap bytes
    |  67112
    V
WiFi Config
    |
    |  Free Heap bytes
    |  67112
    |  64504 <= bytes <= 67112
    |  64504
    V
Display Setup
    |
    |  Free Heap bytes
    |  64504
    |  64176 <= bytes <= 64504
    |  64176
    V
Rover - Not Started
    |
    |  Free Heap bytes
    |  64176
    |  64176 <= bytes <= 129168
    |  129168
    V
Rover - No Fix
    |
    |  Free Heap bytes
    |  129168
    |  32292 <= bytes <= 129168
    |  32292
    V
Rover - Fix
    |
    |  Free Heap bytes
    |  32292
    |
    |  Free heap since last reset
    |  32292 <= bytes <= 166924
    V
rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
    |
    V
Rover - No Fix
    |
    |  Free Heap bytes
    |  177356
    |  79864 <= bytes <= 177356
    |  79864
    V
Rover - Fix
    |
    |  Free Heap bytes
    |  79864
    V
Display Setup
    |
    |  Free Heap bytes
    |  79864
    V
Rover - Not Started
    |
    |  Free Heap bytes
    |  79864
    |  79760 <= bytes <= 79864
    |  79760
    V
Rover - No Fix
    |
    |  Free Heap bytes
    |  79760
    V
Rover - Fix
    |
    |  Free Heap bytes
    |  79760
    |  77744 <= bytes <= 79760
    |  77744
    V
Display Setup
    |
    |  Free Heap bytes
    |  77744
    V
Rover - Not Started
    |
    |  Free Heap bytes
    |  77744
    V
Rover - No Fix
    |
    |  Free Heap bytes
    |  77744
    V
Rover - Fix
    |
    |  Free Heap bytes
    |  77744
    |  75736 <= bytes <= 77744
    |  75736
    V
Display Setup
    |
    |  Free Heap bytes
    |  75736
    V
Rover - Not Started
    |
    |  Free Heap bytes
    |  75736
    V
Rover - No Fix
    |
    |  Free Heap bytes
    |  75736
    V
Rover - Fix
    |
    |  Free Heap bytes
    |  75736
    |  73736 <= bytes <= 75736
    |  73736
    V
Display Setup
    |
    |  Free Heap bytes
    |  73736
    V
Base - Not Started
    |
    |  Free Heap bytes
    |  73736
    |  73736 <= bytes <= 166904
    |  166904
    V
Base-Temp - Settle
    |
    |  Free Heap bytes
    |  166904
    |  79384 <= bytes <= 166904
    |  79384
    V
Display Setup
    |
    |  Free Heap bytes
    |  79384
    V
Base - Not Started
    |
    |  Free Heap bytes
    |  79384
    |  79384 <= bytes <= 166560
    |  166560
    V
Base-Temp - Settle
    |
    |  Free Heap bytes
    |  166560
    |  79388 <= bytes <= 166560
    |  79388
    V
Display Setup
    |
    |  Free Heap bytes
    |  79388
    V
Base - Not Started
    |
    |  Free Heap bytes
    |  79388
    |  79388 <= bytes <= 166560
    |  166560
    V
Base-Temp - Settle
    |
    |  Free Heap bytes
    |  166560
    |  79392 <= bytes <= 166560
    |  79392
    V
Display Setup
    |
    |  Free Heap bytes
    |  79392
    V
Base - Not Started
    |
    |  Free Heap bytes
    |  79392
    |  79392 <= bytes <= 166560
    |  166560
    V
Base-Temp - Settle
    |
    |  Free Heap bytes
    |  166560
    |  79400 <= bytes <= 166560
    |  79400
    V
Display Setup
    |
    |  Free Heap bytes
    |  79400
    V
Base - Not Started
    |
    |  Free Heap bytes
    |  79400
    |  79400 <= bytes <= 166560
    |  166560
    V
Base-Temp - Settle
    |
    |  Free Heap bytes
    |  166560
    |  79392 <= bytes <= 166560
    |  79392
    V
Display Setup
    |
    |  Free Heap bytes
    |  79392
    V
Base - Not Started
    |
    |  Free Heap bytes
    |  79392
    |  79392 <= bytes <= 166560
    |  166560
    V
Base-Temp - Settle
    |
    |  Free Heap bytes
    |  166560
    |  79388 <= bytes <= 166560
    |  79388
    V
Display Setup
    |
    |  Free Heap bytes
    |  79388
    V
Base - Not Started
    |
    |  Free Heap bytes
    |  79388
    |  79388 <= bytes <= 166560
    |  166560
    V
Base-Temp - Settle
    |
    |  Free Heap bytes
    |  166560
    |  79388 <= bytes <= 166560
    |  79388
    V
Display Setup
    |
    |  Free Heap bytes
    |  79388
    V
Rover - Not Started
    |
    |  Free Heap bytes
    |  79388
    V
Rover - No Fix
    |
    |  Free Heap bytes
    |  79388
    V
Rover - Fix
    |
    |  Free Heap bytes
    |  79388
    |  77368 <= bytes <= 79388
    |  77368
    V
Display Setup
    |
    |  Free Heap bytes
    |  77368
    V
Rover - Not Started
    |
    |  Free Heap bytes
    |  77368
    V
Rover - No Fix
    |
    |  Free Heap bytes
    |  77368
    V
Rover - Fix
    |
    |  Free Heap bytes
    |  77368
    |  75384 <= bytes <= 77368
    |  75384
    V
Display Setup
    |
    |  Free Heap bytes
    |  75384
    V
Rover - Not Started
    |
    |  Free Heap bytes
    |  75384
    V
Rover - No Fix
    |
    |  Free Heap bytes
    |  75384
    V
Rover - Fix
    |
    |  Free Heap bytes
    |  75384
    |
    |  Free heap since last reset
    |  73384 <= bytes <= 177356
    V

----------------------------------------------------------------------
State: Display Setup
Free heap bytes upon entry
    79776
    75060
    72452
    69844
    37528
    67112
    64504
    79864
    77744
    75736
    73736
    79384
    79388
    79392
    79400
    79392
    79388
    79388
    77368
    75384

----------------------------------------------------------------------
State: WiFi Config Not Started
Free heap bytes upon entry
    79776
    75060
    72452
    37528
    67112

----------------------------------------------------------------------
State: WiFi Config
Free heap bytes upon entry
    166924
    75060
    72452
    124700
    67112

----------------------------------------------------------------------
State: Rover - Not Started
Free heap bytes upon entry
    69844
    64176
    79864
    77744
    75736
    79388
    77368
    75384

----------------------------------------------------------------------
State: Rover - No Fix
Free heap bytes upon entry
    134388
    129168
    177356
    79760
    77744
    75736
    79388
    77368
    75384

----------------------------------------------------------------------
State: Rover - Fix
Free heap bytes upon entry
    37528
    32292
    79864
    79760
    77744
    75736
    79388
    77368
    75384

----------------------------------------------------------------------
State: Base - Not Started
Free heap bytes upon entry
    73736
    79384
    79388
    79392
    79400
    79392
    79388

----------------------------------------------------------------------
State: Base-Temp - Settle
Free heap bytes upon entry
    166904
    166560
    166560
    166560
    166560
    166560
    166560
`

**Comment by nseidle** [comment]
This is a known issue. See #65. @LeeLeahy2 - I would welcome your help here. The ESPAsyncWebServer library gobbles a lot of resources, all of which I have not yet been able to figure out how to get it to release.
