### ISSUE TITLE
Display Corruption in Setup Mode

### ISSUE THREAD

**Issue by LeeLeahy2** [sparkfun/SparkFun_RTK_Firmware#129]
### Subject of the issue
The RTK Express display get corrupted when walking through all of the states in Setup mode.  I am guessing here that the corruption is occurring during the display of Profile 1 - 4 states.

### Your workbench
* What version of RTK Surveyor firmware are you running?   release_candidate (9b68e43f3e16bf67ed1099e530522d2fb47cf223)
* Are you connected to the device over Bluetooth? What app?   No
* Are you transmitting NTRIP back to the device?  No
* How is everything being powered?  Battery / USB Cable
* Are there any additional details that may help us help you?  No

### Steps to reproduce
1. Power on the RTK Express
2. Press and release the Setup button
3. Repeat step 2 to walk through the entire Setup menu from Mark back to Mark

### Expected behavior
All states should display correctly

### Actual behavior
Display corruption occurs after the WiFi Config state.  Display restored when reaching the Mark state

**Comment by nseidle** [comment]
I believe this is linked to #130. If there's an unterminated string getting in there, it would corrupt the screen.

Please give the [latest commit](https://github.com/sparkfun/SparkFun_RTK_Firmware/commit/42ec4c7973ac29c7a99fb27fa2aa90516bf90ef0) a try.

**Comment by nseidle** [comment]
I believe this is fixed in v2.0. Please re-open if you still have issues.
