### ISSUE TITLE
index.html fails HTML validation

### ISSUE THREAD

**Issue by LeeLeahy2** [sparkfun/SparkFun_RTK_Firmware#133]
### Subject of the issue
The index.html page fails validation.

### Your workbench
* What version of RTK Surveyor firmware are you running?  release_candidate (4dfc4e5b2eba445ab0c2939f6bcaa436444f6c06)
* Are you connected to the device over Bluetooth? What app?   No
* Are you transmitting NTRIP back to the device?   No
* How is everything being powered?   Battery / USB cable
* Are there any additional details that may help us help you?  [[CSS Validator](https://jigsaw.w3.org/css-validator/)](url)

### Steps to reproduce
1. Pass the AP-Config/index.html file to the HTML validator at [https://validator.w3.org/](url)

### Expected behavior
The HTML validator should indicate that everything passes

### Actual behavior
The HTML validator is showing 19 errors

Also note that the HTML source (index.html) does not match the page downloaded to the browser.  The downloaded page has too many errors to validate (>1000).  See the attached file
[view-source_192.168.4.1.zip](https://github.com/sparkfun/SparkFun_RTK_Firmware/files/8703785/view-source_192.168.4.1.zip)

**Comment by nseidle** [comment]
This is not a big enough issue to fix. If anyone wants to tackle it in the future, a PR would be greatly appreciated.
