### ISSUE TITLE
Failed to update Firmware V.2.1

### ISSUE THREAD

**Issue by IngridBerru** [sparkfun/SparkFun_RTK_Firmware#151]
Hello,
Currently, the Sparkfuns ( Rover and Base) have the firmware version v.2.0 ; and I want to update to the new version 2.1 however I experienced the following problems:

*Using the GUI, the device doesn't reset and power down, as a result, the firmware is not updated and the device kept frozen, however, the messages on the GUI say that the device is resetting.
![image](https://user-images.githubusercontent.com/104285477/171507431-c3623427-3767-40f0-a276-5a535c5aee35.png)

*Using Wifi, also It doesn't allow it to update, for example at the end of the updating process the following message appears "OTA could no begin".
![image](https://user-images.githubusercontent.com/104285477/171508006-41a3261c-f357-405d-89ef-838f28ad50d1.png)

Best regards,

**Comment by nseidle** [comment]
The GUI failure is due to a bad partition file. We'll update the GUI shortly.

**Comment by tonycanike** [comment]
I tried to update from V2.0 to V2.1 using the Windows GUI and also via the SD update path.  Was unsuccessful.  Here's the serial log when I tried using the SD card method:



```
SparkFun RTK Facet v2.0-May 26 2022
** Bluetooth broadcasting as: Facet Rover-4DAE **
Menu: Main Menu
1) Configure GNSS Receiver
2) Configure GNSS Messages
3) Configure Base
4) Configure Ports
5) Configure Logging
p) Configure Profiles
s) System Status
f) Firmware upgrade
x) Exit

Menu: Update Firmware Menu
1) Load RTK_Surveyor_Firmware_v1_10.bin
2) Load RTK_Surveyor_Firmware_v1_11.bin
3) Load RTK_Surveyor_Firmware_v1_12.bin
4) Load RTK_Surveyor_Firmware_v2_0.bin
5) Load RTK_Surveyor_Firmware_v2_1.bin
x) Exit
5
Loading RTK_Surveyor_Firmware_v2_1.bin
Update begin failed. Not enough partition space available.

Menu: Update Firmware Menu
1) Load RTK_Surveyor_Firmware_v1_10.bin
2) Load RTK_Surveyor_Firmware_v1_11.bin
3) Load RTK_Surveyor_Firmware_v1_12.bin
4) Load RTK_Surveyor_Firmware_v2_0.bin
5) Load RTK_Surveyor_Firmware_v2_1.bin
x) Exit

```

**Comment by nseidle** [comment]
Sorry the GUI is currently down. We'll have it fixed shortly. 

@tonycanike - Your partitions are set to 2MB preventing v2.1 to be loaded. The GUI will eventually fix partition issues, but in the between times, do you feel like trying the [CLI method](https://sparkfun.github.io/SparkFun_RTK_Firmware/firmware_update/#updating-firmware-from-cli)?

Once we get the partitions sorted, SD and WiFi update paths work again:

![image](https://user-images.githubusercontent.com/117102/171699312-b4313ddf-2689-4c78-ae68-7e6cb1c450ef.png)

**Comment by tonycanike** [comment]
Thanks @nseidle that worked perfectly.

**Comment by PaulZC** [comment]
Hi @IngridBerru / @tonycanike ,

Version 1.1 of the firmware uploader executable is now available. You can download it on its own using the [download button on this page](https://github.com/sparkfun/SparkFun_RTK_Firmware/blob/main/Uploader_GUI/Windows_exe/RTK_Firmware_Uploader_GUI.exe). Or you can download the whole repo using the usual methods. The exe contains the corrected partition file. Please give it a try and let us know if you see any issues.

Thank you,
Paul

**Comment by PaulZC** [comment]
PS. If - like me - you have a very old RTK Surveyor - it may contain a 4MB version of the ESP32. If you have one too, I'm afraid you're restricted to [v1.0 of the GUI](https://github.com/sparkfun/SparkFun_RTK_Firmware/blob/main/Uploader_GUI/Windows_exe/Previous_Version/RTK_Firmware_Uploader_GUI.exe) and [v2.0 of the firmware](https://github.com/sparkfun/SparkFun_RTK_Firmware/blob/main/Binaries/RTK_Surveyor_Firmware_v2_0.bin). At least for now...

You can tell which version you have by looking at the diagnostic messages from the upgrade:

![image](https://user-images.githubusercontent.com/5690545/171743461-85f38d0d-a3a3-4636-90b5-c1b43e0b414e.png)

**Comment by tonycanike** [comment]
> Hi @IngridBerru / @tonycanike ,
> 
> 
> Version 1.1 of the firmware uploader executable is now available. ... The exe contains the corrected partition file. Please give it a try and let us know if you see any issues.
> 

Thanks @PaulZC! I had already upgraded to 2.1 via CLI per @nseidle's suggestion.

**Comment by nseidle** [comment]
Excellent! Glad to hear it.
