### ISSUE TITLE
Setup button doesn't work if powered on in Base Mode (Facet, v2.0 firmware)

### ISSUE THREAD

**Issue by tonycanike** [sparkfun/SparkFun_RTK_Firmware#153]
### Subject of the issue
The Facet setup button is unresponsive to short pushes if the Facet is powered on when configured to be a Base unit.

### Your workbench
SparkFun RTK Facet v2.0-May 26 2022
ZED-F9P firmware: HPG 1.32

### Steps to reproduce
0. Start with device powered on in Rover mode.
1. Use the setup button (short pushes) to select Base mode.   Wait for "Base Started" display.
2. Long push to power off.
3. Long push to power on.
4. Unit powers up in Base mode, 
5. Short pushes of Power/Setup button do not allow change of mode.  Can not enter WiFi config.
6. Long pushes still work to power off and on.

### Expected behavior
Short pushes should allow change of mode.

### Actual behavior
Short pushes are unresponsive.
Can not be put into WiFi config mode to enter fixed base coordinates.
Can not be switched to Rover mode via the button.
Serial mode can be used to switch the Rover mode,   Short pushes work in Rover mode.

Note you must select Base mode, power off, and power back on.    Simply switching from Rover to Base via the button does not disable the short pushes of the button.

This is especially problematic when out in the field and unable to use serial configuration.  Problem was discovered after base was setup over known point and I attempted to put the Facet into WiFi config mode to enter fixed coordinates.

Problem subsequently replicated multiple times on two different units.

I have two Facets and both exhibit this behavior.
I've used serial configuration to reset to factory defaults, problem still exists.
Problem did not exist with V1.12 firmware.
Problem started immediately after upgrading to V2.0 firmware.

**Comment by nseidle** [comment]
Thanks for reporting! Can confirm. We'll get it fixed shortly.

**Comment by nseidle** [comment]
I think I've got it. I'll get an RC up shortly.

**Comment by nseidle** [comment]
Ok - RC June1 with the fix is on the [release page](https://github.com/sparkfun/SparkFun_RTK_Firmware/releases/tag/v2.1). This was a bad bug; sorry for messing up your unit in the field.

Please re-open if you continue to have problems.

**Comment by Firefishy** [comment]
I have a unit stuck in base mode. Would appreciate instructions on how to fix this? How do connect via serial mode?

**Comment by nseidle** [comment]
Sorry about that! See this issue https://github.com/sparkfun/SparkFun_RTK_Firmware/issues/151
