### ISSUE TITLE
v1.2 SDCard not recognized

### ISSUE THREAD

**Issue by Stefal** [sparkfun/SparkFun_RTK_Firmware#17]
### Subject of the issue
The microSD card is not recognized

### Your workbench
* RTK Surveyor 1.2

### Steps to reproduce
Upgrade from 1.1 to 1.2

### Expected behavior
The RTK Surveyor should be able to log on the SD.

### Actual behavior
When I open the "Configure Data Logging" menu, I have these messages:
```
Menu: Logging Menu
SD init failed. Trying again 1 out of 2
SD init failed. Trying again 2 out of 2
SD init failed. Is card present? Formatted?
No microSD card is detected
```

I've tested several SD (FAT32, exFat) with the same results.
If I downgrade to 1.1 I can log on the SD Card.

**Comment by nseidle** [comment]
Here are esptool and SD compatible binaries: [RTK_Surveyor_Firmware_v13RC_May11_combined.zip](https://github.com/sparkfun/SparkFun_RTK_Surveyor/files/6461502/RTK_Surveyor_Firmware_v13RC_May11_combined.zip)

This should show you a debug menu 'd' that will allow you to turn up or down the SPI freq.

**Comment by Stefal** [comment]
I just made a quick test with the firmware 13RC_May11 and.... everything seems to work correctly...strange... I'll test more in depth later, and try another time with the v1.12.

**Comment by nseidle** [comment]
I've downgraded a few units to v1.2 binary and cannot replicate - the SD works for me. I did have one test where the SD failed but it was a mechanical issue - once I re-inserted the SD card it worked.

Please continue to poke. I'll leave this open.

**Comment by Stefal** [comment]
Downgrade to v1.2 from SD card: I can't use the SD Card
Downgrade to v1.2 with esptool:  I can't use the SD Card

With v1.3RC, all the non working SD cards I've tested with v1.2, are working correctly.
🤔

**Comment by nseidle** [comment]
What in the world... I'll keep digging. I've ordered 32GB extreme and 16GB ultra to try to replicate.

Good to know v1.3 is working!

**Comment by Stefal** [comment]
Another RTK Surveyor, with another SD Card (formatted with SD Formatter).
Upgrade from 1.1 to 1.2 with SD load:
```
File move complete
Firmware updated successfully. Rebooting. Good bye!
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:9720
ho 0 tail 12 room 4
load:0x40080400,len:6352
entry 0x400806b8
SD init failed. Trying again 1 out of 2
SD init failed. Trying again 2 out of 2
SD init failed. Is card present? Formatted?
Settings wrong size. Default settings applied
Config file read failed: SD offline
MAX17048 configuration complete
Batt (68%): Voltage: 4.17V Charging: 19.34%/hr Green all good
GNSS configuration complete
WiFi Stopped
Bluetooth broadcasting as: Surveyor Rover-0862
State: Rover - No Fix
```

Upgrade to v1.3 -> I can use the sd card, with SPI set to 8 or 36 Mhz.

**Comment by lukasgraf** [comment]
I'm seeing the same issue (SD card not recognized after update to 1.2):

- I received the RTK Surveyor with firmware 1.1 on it
- I was successful in updating the firmware from 1.1 to 1.2 using the SD load method.
  Worked like a charm, never saw any SD init failures.
- But when I now (on 1.2) enter the Data Logging menu (attempting to enable SD data logging), I also get
   ```
    SD init failed. Trying again 1 out of 2
    SD init failed. Trying again 2 out of 2
    SD init failed. Is card present? Formatted?
    ```
- SD card was formatted using the [SD Formatter](https://www.sdcard.org/downloads/formatter/) tool (as FAT32)
- SD card still mounts and reads fine on my MacBook
- The SD card is a 32GB `Sandisk ExtremePro microSD A1 (microSDHC, 32GB, U3, UHS-I)` (Mfr-No: [`SDSQXCG-032G-GN6MA`](https://shop.westerndigital.com/products/memory-cards/sandisk-extreme-pro-uhs-i-microsd#SDSQXCG-032G-GN6MA))

I will now get `esptool` and give the `1.3` release candidate a try.

Happy to assist in debugging. I've got some time on my hands, just let me know if you need me to try something.

**Comment by lukasgraf** [comment]
And indeed, after upgrading to the `1.3` RC via `esptool`, SD logging now works for me too (same SD card, not reformatted or anything).

**Comment by nseidle** [comment]
Thanks for confirming @lukasgraf. I haven't forgotten about this! I've got two new test microSD cards but the test kit is always at the other office. I hope to poke at this Thursday but for now please continue using and testing [v13 RC May25](https://github.com/sparkfun/SparkFun_RTK_Surveyor/files/6542645/RTK_Surveyor_Firmware_v13RC_May25.zip). I'm freezing this RC and assuming no other issues, releasing v13 early next week.

**Comment by nseidle** [comment]
Closing issue. SD interface has been solved in recent releases.
