### ISSUE TITLE
IP address locked because RTK base not sending NTRIP data

### ISSUE THREAD

**Issue by LeeLeahy2** [sparkfun/SparkFun_RTK_Firmware#175]
### Subject of the issue
The following text is from rtk2go.com:

"...
There is a new Banned IP Event Report associated with your Base Station account.
used on the SNIP NTRIP Caster located at [rtk2go.com:2101](http://rtk2go.com:2101/) (RTK2go).
...
The Last Error Report follows:
...
Client [#C122510] appears to a Rev1 NTRIP Server connecting, Wed 06:02:27.618 PM (local), from ...
A remote NTRIP Server (was a Client) sent us: ====================== (82 chars)
...
Source-Agent: NTRIP SparkFun_RTK_Express/v2.3
...
  =END= (an inbound PUSH-In data connection attempt using the Rev1 form)
PUSH-IN disconnected, never sent ANY data AFTER the NTRIP setup string, marked as bad connection.
Suggestion:: Ensure your GNSS is tracking before connecting.
...
The above was the event that triggered the ban, the below is a summary of how this IP has been used

The IP ... has connected with...
  Agent: NTRIP SparkFun_RTK_Express/v2.3
    Port: [52667~52692], Connections spanning from Wed, 15 June 17:22:50 (then disconnected)
      User: Anon PUSH_In: LPL-Test Connections: 26, Failed: 26 [100.0%], NMEA Sent: 0 (Connected 40:28 MIN:SEC Overall)
      The prior connection lasted: 01:33 MIN:SEC
      And new connections are BANNED
  Agent: NTRIP SparkFun_RTK_Express_v2.3
    Port: [49563~65143], Connections spanning from Tue, 14 June 16:34:26 to Now.
      User: [test@test.com](mailto:test@test.com) MountPt: MH2-79 Connections: 50, Failed: 0 , NMEA Sent: 0 (Connected 13:27:35 (H:M:S) Overall)
      Connected for: 40:55 MIN:SEC
      And new connections are BANNED
  Agent: NTRIP SparkFun_RTK_Facet L-Band_v2.3
    Port: [49339~63877], Connections spanning from Wed, 15 June 04:29:59 (then disconnected)
      User: [test@test.com](mailto:test@test.com) MountPt: MH2-79 Connections: 6, Failed: 0 , NMEA Sent: 0 (Connected 45:52 MIN:SEC Overall)
      The prior connection lasted: 01:40 MIN:SEC
      And new connections are BANNED
  Agent: NTRIP SparkFun_RTK_Surveyor/v1.12
    Port: 60012, Connections spanning from Tue, 14 June 13:56:51 to Now.
      User: Anon PUSH_In: MH2-79 Connections: 1, Failed: 0 , NMEA Sent: 0 (Connected 1 Day 04:07 (HH:MM) Overall)
      Connected for: 1 Day 04:07 (HH:MM)
      And new connections are BANNED

While the IP is banned, it will not be serviced.

Note: Please correct the problem before reconnecting to the Caster.

Regards, The Support team RTK2go"

### Your workbench
* What version of RTK Surveyor firmware are you running?  release_candidate (f62a7d50)
* Are you connected to the device over Bluetooth?  No, connected via WiFi
* How is everything being powered?  Battery / USB-C
* Are there any additional details that may help us help you?  No

### Steps to reproduce
1. Configure the RTK system in base mode with the NTRIP server enabled
2. Power on the RTK system in an interior room away from windows
3. Wait for a while

### Expected behavior
NTRIP server should have WiFi enabled but does not connect to the NTRIP caster until it is ready to send data.  When data stops becoming available, the NTRIP caster connection is broken.

### Actual behavior
The NTRIP caster connection was left connected with no data being sent.  This caused rtk2go.com to ban the IP address for a significant portion of the day.

**Comment by nseidle** [comment]
This will happen if the device connects to RTK2Go, and then fails to upload data. RTK2Go will close the port, and then the RTK firmware will diligently reconnect to RTK2Go. Do this enough times and RTK2Go will ban the IP (as they should). 

[This fix](https://github.com/sparkfun/SparkFun_RTK_Firmware/commit/352f83c0d1d749284a800a84d5f5189b38836c93) is working for me. Please re-open if you still see issues.
