### ISSUE TITLE
Dotted quad IPv4 addresses always fail to parse in settings

### ISSUE THREAD

**Issue by XPav** [sparkfun/SparkFun_RTK_Firmware#274]
Using firmware 2.3, I set the NTRIP Caster Address under Base to a local IP address.    Port is unchanged at 2101, new mountpoint and password are added.

It works!  Using SNIP, I see a Pushed-In stream.

Then I turn off the unit, and turn it back on, and NTRIP Caster Address is reset back to rtk2go.com, and there is no data coming to me.

This also happens when I configure via the Wifi web interface.

edit:  Shown on startup:
```LittleFS Started
SparkFun RTK Facet v2.3-Aug  1 2022
Failed to parse line 45: ntripServer_CasterHost
Reset reason: ESP_RST_SW
Failed to parse line 45: ntripServer_CasterHost
Profile 'Profile1' loaded
```

If I put in a hostname, it works.   If I put in a dotted quad, it does not work.

The IP address is likely being attempted to be decoded as a number in parseline(). 

Dotted quads likely also don't work on the the NTRIP Client and MQTT brokers too.   

A few quick attempts to find a string that's not a number but also is accepted by the host name resolver has failed.

I guess I don't see why "settingValue", which could "possibly" be a string-converted-into-a-number is used on the 20-odd values that should always be strings vs just "str".  Issue 47 doesn't seem to apply here.

**Comment by nseidle** [comment]
Thanks for reporting! Turns out 192.168.1.1 doesn't contain isAlpha(). Should be fixed in next build.
