### ISSUE TITLE
Rover NTRIP Client is started without  a fix

### ISSUE THREAD

**Issue by gdt** [sparkfun/SparkFun_RTK_Firmware#284]
### Subject of the issue

When configured for Rover with NTRIP, the NTRIP connection is sometimes made before there is a fix.  When configured to send GGA to the base (for network RTK), this results in sending a GGA that has empty lat/lon and fixmode 0.  With MaCORS (which is Leica), that leads to "401 Unauthorized" and the connection is closed.

The firmware tries again, and in my test run failed again, and the third time there was a position.

This is bad because it causes unnecessary traffic and also connections that seem misbehaved at the NTRIP server, which might log failures with some anti-DOS rate limits and lock people out (wild speculation).  Even if not it's just noise and not useful, and it makes debugging harder.

One could argue that starting without a fix is only a problem when sending GGA, but getting RTK reference data without a fix isn't really useful but consumes resources anyway, so one can also argue that there's no point starting NTRIP until there's a fix.

### Your workbench
* RTK Express (16MB version)
* 2.4RC from August 15
* No bluetooth connection, device configured for wifi and NTRIP to MaCORS.
* Internal battery is charged and USB power to ESP port.

### Steps to reproduce

To reproduce, configure WiFi NTRIP and ensure that it's working.  Power down the unit and wait long enough that the ephemeris data will be stale; in my case it was several hours and I don't really remember.   Then start tcpdump on the router or someplace that will see the wifi traffic, saving to a file, and power up the Express.   Wait about 30 minutes, watching the fix status, and then go look at the tcpdump data.

While I am seeing the 401 with MaCORS, anyone anywhere should be able to observe the bad GGA being sent, and this execution path should be clear from code inspection (now that one knows to look for it :-).

### Expected behavior

There are two possible expected behaviors:

  * if configured to send GGA, the NTRIP connection is not initiated until there is a fix
  * always, the NTRIP connection is not initiated until there is a fix

I vote for the second, as it makes the needed change simpler, and results in less network traffic (usually on metered cell).  Since time to RTK data from starting the state machine is short, starting on fix will likely result in RTK data soon enough to not delay entering RTK mode, as the first fix is often only a few satellites and sometimes with somewhat old ephemeris data.  Even if it is  a few seconds slower, I think that's ok.   And, with a warm start (ephemeris already valid for all sats above horizon), the F9P probably has a fix before the ESP is done booting, so there won't be a delay.

### Actual behavior

Bad GGA is sent resulting in the server 401'ing the connection.   While that's an odd code and it's more "bad request" than "unauthorized", and perhaps just ignoring it would be more helpful, I don't think I can reasonably file a bug with Leica about this.

**Comment by nseidle** [comment]
Agreed. Will roll into next RC.
