### ISSUE TITLE
RTCM Count No Longer Increments by 1

### ISSUE THREAD

**Issue by YashuSystems** [sparkfun/SparkFun_RTK_Firmware#288]
I updated to v2.3 on a Facet. Should the RTCM count still increment by one as displayed on the oLED when configured as a casting base? I am seeing random increment amounts occurring for each transmit.

**Comment by nseidle** [comment]
The count went from a pseudo frame count (that was close but not quite true) to a byte count. In v2.4 [we've corrected](https://github.com/sparkfun/SparkFun_RTK_Firmware/commit/2e80170916ef800aecbbb48c765c210591c89c95) it back to a frame count. You can try the [release candidate](https://github.com/sparkfun/SparkFun_RTK_Firmware/releases/tag/v2.4RC) out if you'd like the count to change back to frames.
