### ISSUE TITLE
Assisted Base should not be L-band only

### ISSUE THREAD

**Issue by gdt** [sparkfun/SparkFun_RTK_Firmware#304]
The docs talk about "Assisted Base" where a Facet is run in Rover mode getting reference data, and then when in RTK FIX, set to temporary base to survey in, with the critical point (not quite 100% clear) is that the positions which are averaged are RTK FIX solutions because the plumbing for the L Band correction stream remains active **even though the device is in base mode**.

WIth a non-L-band unit, this logical flow is equally sensible: one can position with a good sky view from some remote base or RTN.   This requires a "Base with NTRIP client" mode analogous to how L band data is still used during survey in.  really, it could be arriving over SPP, or NTRIP client.

I'm not claiming this is a big deal or high priority, just that it doesn't make sense for "use RTK to locate Base" to be L-band only.

**Comment by nseidle** [comment]
Excellent point. [Docs updated](https://docs.sparkfun.com/SparkFun_RTK_Firmware/configure_base/#assisted-base).
