### ISSUE TITLE
Firmware update via SD causes Guru Meditation Error

### ISSUE THREAD

**Issue by pyrog** [sparkfun/SparkFun_RTK_Firmware#315]
### Subject of the issue
Can't boot if the SD card is inserted.
Can't upgrade firmware from 2.4 RC either from USB or WIFI.

This version seemed usable, until today. Does the SD was corrupted ??

### Your workbench
* RTK Surveyor Firmware: v2.4-Aug 11 2022 

### Steps to reproduce
Without SD card, the Surveyor boot correctly: the USB console and the web server are running :smiley:

From the console, I insert the SD card. I could list the files but I **can't upgrade the firmware**.

```
Menu: Update Firmware Menu
1) Load RTK_Surveyor_Firmware_v2_0.bin

2) Load RTK_Surveyor_Firmware_v2_3RC-June28.bin

3) Load RTK_Surveyor_Firmware_v2_4.bin

x) Exit
3
Loading RTK_Surveyor_Firmware_v2_4.bin

Guru Meditation Error: Core  1 panic’ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400d40cb  PS      : 0x00060b30  A0      : 0x800e24fc  A1      : 0x3ffd3ce0  
A2      : 0x00000000  A3      : 0x3ffc758c  A4      : 0xd2a6e2ab  A5      : 0x3ffd3cdc  
A6      : 0x3ffcc16c  A7      : 0x3ffd3cdc  A8      : 0x80104112  A9      : 0x3ffd3c80  
A10     : 0x00000028  A11     : 0x3ffd3cdc  A12     : 0x00000028  A13     : 0x3ffd3d20  
A14     : 0x3ffd3ca0  A15     : 0x00000008  SAR     : 0x00000020  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000270  LBEG    : 0x40092d39  LEND    : 0x40092d49  LCOUNT  : 0xfffffff8  


Backtrace:0x400d40c8:0x3ffd3ce00x400e24f9:0x3ffd3d40 0x400e28af:0x3ffd45e0 0x400e78f7:0x3ffd4600 0x400e79c4:0x3ffd4620 0x400e79fb:0x3ffd4640 0x40107809:0x3ffd4660 




ELF file SHA256: 0000000000000000

Rebooting…
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1240
load:0x40078000,len:13012
load:0x40080400,len:3648
entry 0x400805f8
Display not detected
ZED-F9P firmware: HPG 1.13

LittleFS Started
SparkFun RTK Surveyor v2.4-Aug 11 2022
Reset reason: ESP_RST_PANIC

```

### Actual behavior
If the SD card is inserted in the device when booting, the power on led is lit, all other leds are off.
After a while, the PPS led is blinking at 1 Hz.

The terminal display : 
```
Unknown: bootcode.bin

Unknown: ._RTK_Surveyor_Firmware_v2_0.bin

Unknown: ._RTK_Surveyor_Firmware_v2_3RC-June28.bin

Unknown: ._RTK_Surveyor_Firmware_v2_4.bin

microSD: Online
Settings line 21 too long
Settings line 22 too long
Settings line 23 too long
Settings line 24 too long
Settings line 25 too long
Settings line 26 too long
Settings line 27 too long
Settings line 28 too long
Failed to read line 29 from settings file
Failed to read line 30 from settings file
Failed to read line 31 from settings file
Failed to read line 32 from settings file
…
Failed to read line 3910 from settings file
Failed to read line 3911 from settings file
Failed to read line 3912 from settings file
Failed to read line 3913 from settings file
Failed to read line 3914 from settings file

```
and so on…

**Comment by pyrog** [comment]
SD card was reformatted and erased: work fine 😃 

### Expected behavior
If the settings file or the file system are corrupted:
- stop to read lines from settings file after a timeout ?
- handle this error better (i.e. stop after 100 lines ?)

**Comment by nseidle** [comment]
We have a lot of protection in place:

* If an SD cannot be mounted or read, we [give up and continue booting](https://github.com/sparkfun/SparkFun_RTK_Firmware/blob/main/Firmware/RTK_Surveyor/Begin.ino#L251).
* If a settings file is [not available or readable](https://github.com/sparkfun/SparkFun_RTK_Firmware/blob/main/Firmware/RTK_Surveyor/NVM.ino#L311), give up and use defaults.

I don't doubt your unit failed to boot but I'm having a hard time replicating and fixing this. I don't have a reliable way to corrupt an SD card, or in the same way your card was corrupted.

If an SD card is corrupt, it's hard to say how the system will fail. Sounds like you're up and running with a SD card reformat. If you have additional debug info in the future, please post it and we'll continue to improve.

**Comment by pyrog** [comment]
FYI, the SD card was reformatted and **erased** it (wrote 2 times on all bytes).
The card was/is healthy (the issue is not hardware).

> We have a lot of protection in place:

https://github.com/sparkfun/SparkFun_RTK_Firmware/blob/cd683bf8710661f986ebb948b2b271098891e2ea/Firmware/RTK_Surveyor/NVM.ino#L329

https://github.com/sparkfun/SparkFun_RTK_Firmware/blob/cd683bf8710661f986ebb948b2b271098891e2ea/Firmware/RTK_Surveyor/NVM.ino#L338-L344

I suggest to give up too if **line number is abnormally too big** (i.e. 1024):

```C
if (lineNumber == 0 or lineNumber >= 1024)
{ 
   //If we can't read the first line of the settings file, give up 
   Serial.println("Giving up on settings file"); 
   break; 
 }
```

**Comment by pyrog** [comment]
### Steps to reproduce
* copy i.e. SFE_Surveyor_Settings_1.txt to SFE_Surveyor_Settings_4.txt
* Edit  Settings size to 100000
* Add long string 
* Duplicate file content many times 
* Save it
* Insert the SD card and start the device

Display on terminal:

```
Warning: Settings size is 1000000 but current firmware expects 4496. Attempting to use settings from file.
Settings line 169 too long
Settings line 170 too long
Unknown setting 80790879879087897987979807987907 097907907988

Settings line 172 too long
Settings line 173 too long
Unknown setting 80790879879087897987979807987907 097907907988

Settings line 175 too long
Settings line 176 too long
Unknown setting 80790879879087897987979807987907 097907907988
…

Settings line 2174117 too long
Settings line 2174118 too long
Unknown setting 80790879879087897987979807987907 097907907988

```
After hours, the loop seem ever ending.
Only the yellow PPS led is blinking at 1 hz.

**Comment by pyrog** [comment]
Stop at line 2269621.

Led Pair is blinking and led 100 cm is lit (device is indoor)
