### ISSUE TITLE
Copy ubx files by usb cable or FTP?

### ISSUE THREAD

**Issue by amlago** [sparkfun/SparkFun_RTK_Firmware#323]
I want to copy the ubx files without having to remove the micro sd.
Would it be possible to copy ubx files by usb cable?
Or implement an ftp over wifi just to access these ubx files?
Either method would be great and would allow easy access to ubx files for post processing.

**Comment by tonycanike** [comment]
This is a good idea. 

Deleting files from the SD card would be useful to clean up the card. 

Sending files to the card would be useful too.  Would help for updating profiles (after editing on a computer) and saving a new firmware version to the card 

This would save a lot of fussing trying to get the card in and out of the Facet.  There's not a lot of room for fingers and those cards are small. The card sometimes misses the card reader and goes into the Facet case, where it rattles around until I take the Facet apart.

**Comment by nseidle** [comment]
A fine idea. It will take us a bit to implement. We may use [ZModem](https://en.wikipedia.org/wiki/ZMODEM) as we've used it before on other products.

**Comment by nseidle** [comment]
Ah, we also have file transfer over WiFi in the works.

**Comment by amlago** [comment]
Good news, we keep in touch.

**Comment by pyrog** [comment]
> The card sometimes misses the card reader and goes into the Facet case, where it rattles around until I take the Facet apart.

Same issue with the Surveyor and Express. The slot could be redesigned see #342.

> We may use [ZModem](https://en.wikipedia.org/wiki/ZMODEM) as we've used it before on other products.
> Ah, we also have file transfer over WiFi in the works.

SD card file server over HTTP is highly anticipated 😃 

Instead of using ZModem over USB, could you implement one of the following protocols?

-  [USB mass storage device class](https://en.wikipedia.org/wiki/USB_mass_storage_device_class)
- [OBEX](https://en.wikipedia.org/wiki/OBject_EXchange) (It could be used over BT too)

It could be more simple for end user?

**Comment by amlago** [comment]
Fantastic. This is really good.
Nice job.

Merry Christmas!

**Comment by amlago** [comment]
Facet v2.7 12/26
The file explorer is an excellent idea.

1) Downloading files from a Win 10 notebook went smoothly.
2) From an Android cell phone I got different results depending on the web browser used.
With Chrome the download is almost always successful.
With other browsers like Dolphin Brownser the download never happened.

**Comment by amlago** [comment]
@nseidle
  I know it's a lot of work and time consuming but adding 2 buttons to the explorer, one to select all and one to deselect all, would be great.
Thank you for your great work.

**Comment by nseidle** [comment]
> adding 2 buttons to the explorer, one to select all and one to deselect all, would be great.

Ah! A great idea. I will add.

**Comment by nseidle** [comment]
Global checkbox added:

![image](https://user-images.githubusercontent.com/117102/209883361-5c752593-9c9a-4bcd-8f72-8079a708f0ae.png)

**Comment by amlago** [comment]
Excelente

**Comment by nseidle** [comment]
This has been implemented in [v3.0 firmware](https://github.com/sparkfun/SparkFun_RTK_Firmware/releases/tag/v3.0).
