### ISSUE TITLE
Close all tabs, by default, on WiFi config page

### ISSUE THREAD

**Issue by amlago** [sparkfun/SparkFun_RTK_Firmware#329]
Simple request on the Configuration of the Facet by wifi

1) When opening the configuration page in the address 192.168.4.1, the GNSS Configuration tab is displayed.
While this may be useful for some beginners, in my case it's an extra touch of the screen to close it and go to the tab I want to use.
Although I can slide the screen, I find it more practical to go directly to the tab that I am going to configure.

2) I request if possible, that the tabs are all closed when opening the configuration page.

Cheers

**Comment by nseidle** [comment]
Agreed. GNSS now closed by default when page is loaded.

**Comment by nseidle** [comment]
In release v2.6.
