### ISSUE TITLE
EOL characters change order part way through settings file  (LFCR, then CRLF)

### ISSUE THREAD

**Issue by tonycanike** [sparkfun/SparkFun_RTK_Firmware#331]
### Subject of the issue
Halfway through the settings files, the end of line characters change order, creating the appearance of extra blank lines in the first half of the file.  This is annoying when editing the files to enter coordinates for the base.

In the first half of the file, the order is LF-CR.
In the second half, it's CR-LF.

The LF-CR order gives the appearance of extra blank lines on Windows boxes.

### Your workbench
v2.5-Sep 19 2022

### Steps to reproduce
It wasn't always this way.   I found an old settings file on my PC (v1.10-Feb 21 2022) that had CR-LF through the whole file.

### Expected behavior
Line endings should be CR-LF through the whole file.

**Comment by gdt** [comment]
I'm seeing problems, which I think are the same, but I hadn't chased it down enough to file an issue.

**Comment by tonycanike** [comment]
For me this isn't a problem, just an annoyance.

**Comment by gdt** [comment]
It's a bug whether or not it bothers you :-)  But seriously, all of these things could be processed by scripts etc. and wrong content is maybe going to cause trouble, and not going to do any good.

**Comment by nseidle** [comment]
I agree it's Not Right®. Should be easy enough to fix.

**Comment by tonycanike** [comment]
> But seriously, all of these things could be processed by scripts

Good point.

**Comment by nseidle** [comment]
![image](https://user-images.githubusercontent.com/117102/191590786-599ed4b5-479d-428e-a7c9-6fea108389bc.png)

In next RC.

**Comment by tonycanike** [comment]
Awesome, thanks!
