### ISSUE TITLE
Choose rover or base mode in Ap Config and reset.

### ISSUE THREAD

**Issue by amlago** [sparkfun/SparkFun_RTK_Firmware#335]
Most of the time I configure my Facet in the field.

1) I would like to choose the rover or base mode and that when exiting and resetting it is placed in the chosen mode.

Something similar can already be done in the serial configuration on the PC.
This makes it faster to start working and avoids pressing the power button to extend its useful life.
The truth is that the useful life of the power button is something that worries me since if it fails I am thousands of km from Colorado.
Cheers

**Comment by nseidle** [comment]
Ok, we'll add.

> The truth is that the useful life of the power button is something that worries me since if it fails I am thousands of km from Colorado.

Hah! The buttons have a rated life of >1 million cycles. I'm not sure if I will believe the switch manufacturer, but If you break the button, I will send you 2 new overlays for repair :)

**Comment by tonycanike** [comment]
Very nice, thanks,this is a good idea. 

I'm getting used to simply bringing up the WiFi AP config every time I use my Facets.  After a few moments to connect my phone to the Facet's WiFi AP, it's as good as any mobile app.

**Comment by nseidle** [comment]
![image](https://user-images.githubusercontent.com/117102/194949227-d7617346-60e8-4b04-a99e-3dcd13fe759a.png)

Added

**Comment by amlago** [comment]
It looks great, it will be very practical in the field.

**Comment by tonycanike** [comment]
Thank you!

**Comment by nseidle** [comment]
In release v2.6.
