### ISSUE TITLE
Inconsistent Serial Menu names

### ISSUE THREAD

**Issue by tonycanike** [sparkfun/SparkFun_RTK_Firmware#340]
### Subject of the issue
Menu titles are inconsistent with the choice in the higher-level menu used to access the sub-menu.

### Your workbench
Facet
Firmware V2.5 release

I noted the menu choice to "Configure GNSS Receiver" takes one to a sub-menu titled "GNSS Menu".   
The menu choice to "Configure GNSS Messages" takes one to a sub-menu titled "Messages Menu".

The title "GNSS Menu" could be inferred as to refer to either of those menus.

Minor issue to be sure, it's probably only a concern when folks like us are reporting issues :)

I did not exhaustively check all the menus for consistent naming agreement between the menu title displayed when one is in a menu, and the wording of the higher-level menu selection that takes one into the menu.

**Comment by pyrog** [comment]
I didn't check too, but labels should be consistent with Wifi AP settings.

**Comment by tonycanike** [comment]
Looks awesome, thanks!  Appreciate it @nseidle !
