### ISSUE TITLE
Add Device Id to WiFi Config Page Header  (last 4 of BT Mac?)

### ISSUE THREAD

**Issue by tonycanike** [sparkfun/SparkFun_RTK_Firmware#341]
### Subject of the issue
When running static raw collections for PPP (OPUS, etc.), it would be useful to see a unique identifier in the header of the WiFi Config Page so we can tie screen shots of the configuration to specific devices.  

Taking screen shots of this page documents many important aspects of the static collection session; it would help if the page had a unique id for the receiver so we know which is what when we're sorting through the screen shots on our phones.

It would be very convenient if the unique id is the same as the four digits shown on the OLED screen; I believe they are the last 4 digits of the BT MAC.   

See #344 and #343 

### Your workbench
2.5 release

**Comment by nseidle** [comment]
![image](https://user-images.githubusercontent.com/117102/194945806-01d855c6-f841-43fe-b30f-96da00d075f6.png)

It's getting busy up top. Let me know if there's a better place for this info.

**Comment by nseidle** [comment]
In release v2.6.
