### ISSUE TITLE
Redesign the SD card slot

### ISSUE THREAD

**Issue by pyrog** [sparkfun/SparkFun_RTK_Firmware#342]
### Subject of the issue
The SD card is difficult to insert or remove, and sometime goes inside the case (Surveyor and Express, Facet).

### Expected design

- Add i.e. a chamfer to remove (insert ?) the SD card more easily.
- Add a part on the inside face of the end plate to prevent the card to miss the reader slot.

@nseidle Could you share the 3D design of the end plate ?
The [End_Plate_3.gcode](https://github.com/sparkfun/SparkFun_RTK_Surveyor/blob/main/Enclosure/End_Plate_3.gcode) contain only the holes, not the part itself.

**Comment by tonycanike** [comment]
There's a separate repository for the hardware.  I've put an issue or two there.  Not sure if this is what @nseidle wants us to do.

https://github.com/sparkfun/SparkFun_RTK_Facet
