### ISSUE TITLE
Add Device Id to log file (last 4 of BT Mac in $GNTXT message?)

### ISSUE THREAD

**Issue by tonycanike** [sparkfun/SparkFun_RTK_Firmware#346]
### Subject of the issue
When running multiple static raw collections for PPP (OPUS, etc.), it would be useful to have a device identifier in the beginning of the log file.  Perhaps put the last 4 digits of the BT MAC in a $GNTXT message?

Also see #341 and #344 

When post-processing raw data from multiple collection sessions using multiple devices, it is necessary to be able to double-check which data file came from which occupation session.  Being able to correlate hand-written field notes about the collection session with each individual log file is very important.

My hand-written notes typically contain information such as the occupied survey marker, instrument height, start time, end time, and device id (the last 4 of the BT MAC as displayed on the OLED.)

Having the device ID (last 4 of BT MAC?  Or whole BT MAC?)  in the beginning of the log file would be very helpful.

### Your workbench
Facet with v2.6 of the firmware

**Comment by nseidle** [comment]
![image](https://user-images.githubusercontent.com/117102/194946005-e5012742-ac3d-4f08-ab3a-7016ff32df8e.png)

Added

**Comment by tonycanike** [comment]
Wonderful, thank you!

**Comment by nseidle** [comment]
In version 2.6 release.
