### ISSUE TITLE
Document North Reference Point for Facet

### ISSUE THREAD

**Issue by tonycanike** [sparkfun/SparkFun_RTK_Firmware#350]
### Subject of the issue
Facet documentation should contain the identification of the North Reference Point.

The forum post about the TOP106 north reference point triggered a thought.

What is the north reference point for the Facet?   There's an arrow molded into the case on the bottom, and I've always just assumed the arrow should point north.  But on many GNSS receivers, the north reference is the control panel (MMI - man machine interface as discussed in the NGS OPUS webinars.)  I've search the Sparkfun documentation but haven't found any definitive information.  Perhaps it's there and I missed it.

As an approximation, I use the SFETOP106 antenna calibration for post-processing data from the Facet, as the Facet contains the TOP106 internally. I make a small adjustment for the different ARP-APC offsets between the Facet and the TOP106. 
Reference:      https://forum.sparkfun.com/viewtopic.php?f=116&t=57754

Or does the NGS decide what the NRP is and we just have to wait for them?

**Comment by nseidle** [comment]
We are currently waiting for the NGS to calibrate the Facet. Once that is complete we can document it. For now, it's on an indefinite hold by the NGS; last we heard their receiver was down and they were having equipment difficulties at the same time they had a record high number of calibration requests.

**Comment by tonycanike** [comment]
Thanks, makes sense. I'll close this.
