### ISSUE TITLE
Unit does not always reset after exiting WiFi config

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Firmware#357]
Pressing the 'Exit and Reset' button in the AP config page usually, but not always resets the unit.

**Comment by amlago** [comment]
What is said has happened to me several times.
To solve it I have tried, after saving the data, a timeout of 10 seconds.
Only then did I press the 'Exit and Reset' button.
It seems to work but it could be a coincidence.

**Comment by nseidle** [comment]
We've added a send/confirm receipt protocol for the Save and Reset buttons that solves this. RC v2.7 will be available shortly.

**Comment by nseidle** [comment]
This has been implemented in [v3.0 firmware](https://github.com/sparkfun/SparkFun_RTK_Firmware/releases/tag/v3.0).
