### ISSUE TITLE
Regarding WIFI Configuration: details to add or correct

### ISSUE THREAD

**Issue by amlago** [sparkfun/SparkFun_RTK_Firmware#378]
Facet v2.7 01/06/23
WIFI Configuration

1) In the File Manager tab, when deleting a file with the Delete button, it would be good to add a confirm option, to avoid accidental deletion.
2) In the Base Configuration tab, in the list of saved base coordinates, it would be good to also add an option to confirm, when deleting a base, to avoid accidental deletion.
3) It is a question. Does the Wi-Fi connection have a timeout while in configuration mode if nothing is done?
Or does it disconnect?
4) When changing profiles, my Facet has been reset while in WIFI configuration mode
5) Regarding the list of saved base coordinates, it would be good if it could be copied from profile to profile.

**Comment by nseidle** [comment]
These are 5 separate discussions :) Please create a different issue for each one.

1 & 2) Ok - separate issue #381.

3) Yes, and good point. I'll add the following to the docs: 

The device will continue to try to connect to WiFi if a connection is not made. The connection timeout starts at 15 seconds and increases by 15 seconds with each failed attempt. For example, 15, 30, 45, etc seconds are delayed between each WiFi connection attempt.

4) Ok. Separate issue #382.

5) Separate issue #383. The common coordinates are stored in a file assigned to the profile #. What you are asking is the ability to copy certain things between profiles. I'll see what I can do. It may be awhile.
