### ISSUE TITLE
How to disable powering the RTK Surveyor from USB-C ?

### ISSUE THREAD

**Issue by pyrog** [sparkfun/SparkFun_RTK_Firmware#38]
### Subject of the issue
When connecting the device to a smartphone (e.g. to log the F9P output), it draw the smartphone battery.

- Is it possible to cut the MEAS jumper?
- Or to use a USB splitter Y cable?

<img width="762" alt="Capture d’écran 2021-06-14 à 23 08 17" src="https://user-images.githubusercontent.com/2158081/121959722-6f710180-cd65-11eb-83c2-964ee83da944.png">

**Comment by nseidle** [comment]
Cutting the MEAS jumper on the u-blox USB is a fine way to prevent the device from drawing power from your phone.

**Comment by pyrog** [comment]
Thank you 😙
