### ISSUE TITLE
Copy commonly used coordinates between profiles

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Firmware#383]
Moved from issue #378 

> Regarding the list of saved base coordinates, it would be good if it could be copied from profile to profile.

The common coordinates are stored in a file assigned to the profile #. What you are asking is the ability to copy certain things between profiles. I'll see what I can do. It may be awhile.

**Comment by tonycanike** [comment]
Could this be done on one's phone?  I haven't tried, but just wondering.

Download this file from the SD card to your phone:   StationCoordinates-Geodetic_0.csv   (Profile1 I believe)
On your phone copy that file to StationCoordinates-Geodetic_1.csv
Upload the file from your phone to the SD card:  StationCoordinates-Geodetic_1.csv  (Profile2 I believe)

**Comment by amlago** [comment]
Tony: I'll try to carry out your advice.
I've never created coordinate files by hand for the Facet, but it looks very useful.

**Comment by nseidle** [comment]
Do we still need these feature? I'm really leaning away from it. Tony's solution is a good one and a fine way to set coordinates for various profiles.

**Comment by amlago** [comment]
Thank you. I think there are other more important things before this. I would say don't listen to this.
I'll deal with the coordinate files manually for now.
Greetings

**Comment by nseidle** [comment]
I appreciate your understanding. Thank you! Closing.
