### ISSUE TITLE
"Assisted Base" resource don't work

### ISSUE THREAD

**Issue by eduardobuenof** [sparkfun/SparkFun_RTK_Firmware#386]
### Subject of the issue
Describe your issue here. Additionally, screenshots are easy to paste into github.

I am trying to use the "Assisted Base" resource (https://docs.sparkfun.com/SparkFun_RTK_Firmware/configure_base/#assisted-base), but it is not connect to the NTRIP Client, I believe the access credentials are correct because in "Rover" mode it works perfectly, however when switching to "Base" mode it does not connect to the server by NTRIP. Is this a FW bug? I'm using the latest version (3.0)

### Your workbench
* What version of RTK firmware are you running? RTK_Surveyor_Firmware_v3_0
* 
* This can be found when the serial menu is opened (also in the settings.txt file, and in the serial output at power up).

**###TERMINAL COM###**

Display started
ZED-F9P firmware: HPG 1.32
LittleFS Started
SparkFun RTK Express v3.0-Jan 19 2023
microSD: Online
Profile 'GPS_portable' loaded
MAX17048 configuration complete
Batt (87%): Voltage: 4.14V Discharging: -1.66%/hr Green
GNSS configuration complete
Accelerometer configuration complete
System time set to: Thursday, January 26 2023 13:20:30
*WIFI_OFF
*NTRIP_CLIENT_OFF
NTRIP Client start
NTRIP_CLIENT_ON
State: Rover - No Fix, 2023-01-26 13:20:33.106
Batt (87%): Voltage: 4.14V Discharging: -1.66%/hr Green
WIFI_CONNECTING
NTRIP_CLIENT_WIFI_STARTED
State: Rover - Fix, 2023-01-26 13:20:33.183
Connecting WiFi... SD card size: 7.2 GB / Free space: 7.2 GB

WIFI_CONNECTED
WiFi IP address: 172.17.1.45 RSSI: -41
NTRIP_CLIENT_WIFI_CONNECTED
Rover Accuracy (m): 296.8208
Batt (87%): Voltage: 4.14V Discharging: -1.66%/hr Green
Log file name: SFE_Express_230126_132039.ubx
NTRIP Client connecting to gps-ntrip.ibge.gov.br:2101
NTRIP Client connected
NTRIP Client sending credentials: -I hid this information-
NTRIP Client serverRequest size: 107 of 515 bytes available
NTRIP Client sending server request:
GET /UFPR0 HTTP/1.0
User-Agent: NTRIP SparkFun_RTK_Express_v3.0
Authorization: Basic ZWR1YmY6Mzc2MDA2

NTRIP_CLIENT_CONNECTING
Log file size: 151 - Generation rate: 0.0kB/s
NTRIP_CLIENT_CONNECTED
Rover Accuracy (m): 6.2680
Rover Accuracy (m): 5.5900
Batt (87%): Voltage: 4.14V Discharging: -1.66%/hr Green
Log file size: 14268 - Generation rate: 2.8kB/s
Rover Accuracy (m): 5.1403
Rover Accuracy (m): 5.0615
State: Rover - RTK Float, 2023-01-26 13:20:49.406
Batt (87%): Voltage: 4.09V Discharging: -1.25%/hr Green
Log file size: 36496 - Generation rate: 4.4kB/s
Rover Accuracy (m): 2.8656
WiFi IP address: 172.17.1.45 RSSI: -39
Rover Accuracy (m): 1.9042
Rover Accuracy (m): 1.5496
State: Rover - Fix, 2023-01-26 13:20:54.112
Batt (87%): Voltage: 4.09V Discharging: -1.25%/hr Green
Log file size: 61919 - Generation rate: 5.1kB/s
Rover Accuracy (m): 1.5709
Rover Accuracy (m): 1.6116
Batt (87%): Voltage: 4.09V Charging: 2.50%/hr Green
Log file size: 87668 - Generation rate: 5.1kB/s
Rover Accuracy (m): 1.6596
Rover Accuracy (m): 1.7195
WiFi IP address: 172.17.1.45 RSSI: -37
Batt (87%): Voltage: 4.09V Charging: 2.50%/hr Green
Rover Accuracy (m): 1.7903
Log file size: 114326 - Generation rate: 5.3kB/s

SparkFun RTK Express v3.0-Jan 19 2023
** Bluetooth broadcasting as: Express Rover-373E **
Menu: Main
1) Configure GNSS Receiver
2) Configure GNSS Messages
3) Configure Base
4) Configure Ports
5) Configure Logging
6) Configure WiFi
p) Configure User Profiles
r) Configure Radios
s) Configure System
f) Firmware upgrade
x) Exit
1

Menu: GNSS Receiver
1) Set measurement rate in Hz: 4.00000
2) Set measurement rate in seconds between measurements: 0.25000
3) Set dynamic model: Stationary
4) Set Constellations
5) Toggle NTRIP Client: Enabled
6) Set Caster Address: gps-ntrip.ibge.gov.br
7) Set Caster Port: 2101
8) Set Caster User Name: -I hid this information-
9) Set Caster User Password: -I hid this information-
10) Set Mountpoint: UFPR0
11) Set Mountpoint PW:
12) Toggle sending GGA Location to Caster: Enabled
x) Exit
x

SparkFun RTK Express v3.0-Jan 19 2023
** Bluetooth broadcasting as: Express Rover-373E **
Menu: Main
1) Configure GNSS Receiver
2) Configure GNSS Messages
3) Configure Base
4) Configure Ports
5) Configure Logging
6) Configure WiFi
p) Configure User Profiles
r) Configure Radios
s) Configure System
f) Firmware upgrade
x) Exit
3

Menu: Base
1) Toggle Base Mode: Use Survey-In
2) Set minimum observation time: 60 seconds
3) Set required Mean 3D Standard Deviation: 1.000 meters
4) Set required initial positional accuracy before Survey-In: 0.500 meters
6) Toggle NTRIP Server: Disabled
11) Select survey-in radio: Bluetooth
x) Exit
x

SparkFun RTK Express v3.0-Jan 19 2023
** Bluetooth broadcasting as: Express Rover-373E **
Menu: Main
1) Configure GNSS Receiver
2) Configure GNSS Messages
3) Configure Base
4) Configure Ports
5) Configure Logging
6) Configure WiFi
p) Configure User Profiles
r) Configure Radios
s) Configure System
f) Firmware upgrade
x) Exit
x
WiFi IP address: 172.17.1.45 RSSI: -39
Rover Accuracy (m): 1.8218
Batt (87%): Voltage: 4.09V Charging: 2.50%/hr Green
Log file size: 212668 - Generation rate: 19.7kB/s
State: Rover - RTK Float, 2023-01-26 13:21:23.340
Rover Accuracy (m): 0.4017
Rover Accuracy (m): 0.4100
Batt (87%): Voltage: 4.09V Charging: 2.50%/hr Green
Log file size: 240467 - Generation rate: 5.6kB/s
State: Rover - Fix, 2023-01-26 13:21:28.828
Rover Accuracy (m): 0.4318
Rover Accuracy (m): 0.4795
Batt (87%): Voltage: 4.09V Charging: 2.50%/hr Green
Log file size: 266955 - Generation rate: 5.3kB/s
Rover Accuracy (m): 0.5286
WiFi IP address: 172.17.1.45 RSSI: -41
Rover Accuracy (m): 0.5849
Rover Accuracy (m): 0.6352
Batt (87%): Voltage: 4.11V Charging: 1.87%/hr Green
Log file size: 293939 - Generation rate: 5.4kB/s
Rover Accuracy (m): 0.6920
Rover Accuracy (m): 0.7428
Batt (87%): Voltage: 4.11V Charging: 1.87%/hr Green
Log file size: 319694 - Generation rate: 5.2kB/s
State: Rover - RTK Float, 2023-01-26 13:21:43.425
Rover Accuracy (m): 0.5462
Rover Accuracy (m): 0.3545
WiFi IP address: 172.17.1.45 RSSI: -40
Batt (87%): Voltage: 4.11V Charging: 1.87%/hr Green
Log file size: 345688 - Generation rate: 5.2kB/s
Rover Accuracy (m): 0.2994
Rover Accuracy (m): 0.2691
Rover Accuracy (m): 0.2488
Batt (87%): Voltage: 4.11V Charging: 1.87%/hr Green
Log file size: 373340 - Generation rate: 5.5kB/s
Rover Accuracy (m): 0.2381
State: Display Setup, 2023-01-26 13:21:56.469
Batt (87%): Voltage: 4.11V Charging: 1.87%/hr Green
Log file size: 399283 - Generation rate: 5.2kB/s
WiFi IP address: 172.17.1.45 RSSI: -41
State: Base - Not Started, 2023-01-26 13:22:00.573
WIFI_OFF
NTRIP Client connection to caster was broken
NTRIP_CLIENT_ON
*WIFI_OFF
RTCM parser error maxLength: 61 bytes
RTCM parser error maxLength: 71 bytes
RTCM parser error maxLength: 86 bytes
State: Base-Temp - Settle, 2023-01-26 13:22:02.125
Waiting for Horz Accuracy < 0.50 meters: 0.24
Resetting survey
Survey started. This will run until 60 seconds have passed and less than 1.000 meter accuracy is achieved.
State: Base-Temp - Survey Started, 2023-01-26 13:22:08.058
Batt (87%): Voltage: 4.11V Charging: 1.87%/hr Green
Log file size: 427987 - Generation rate: 5.7kB/s
Time elapsed: 1 Accuracy: 32 SIV: 20
Time elapsed: 2 Accuracy: 32 SIV: 22
Time elapsed: 2 Accuracy: 32 SIV: 22
Time elapsed: 3 Accuracy: 32 SIV: 21
Time elapsed: 3 Accuracy: 32 SIV: 21
Time elapsed: 4 Accuracy: 32 SIV: 21
Time elapsed: 4 Accuracy: 32 SIV: 21
Time elapsed: 5 Accuracy: 32 SIV: 22
Time elapsed: 5 Accuracy: 32 SIV: 22
Time elapsed: 6 Accuracy: 32 SIV: 22
Batt (87%): Voltage: 4.11V Charging: 1.87%/hr Green
Log file size: 435488 - Generation rate: 1.5kB/s
Time elapsed: 6 Accuracy: 32 SIV: 22
Time elapsed: 7 Accuracy: 32 SIV: 21
Time elapsed: 7 Accuracy: 32 SIV: 21
Time elapsed: 8 Accuracy: 32 SIV: 20
Time elapsed: 8 Accuracy: 32 SIV: 20
WIFI_CONNECTING
NTRIP_CLIENT_WIFI_STARTED
Connecting WiFi...
WIFI_CONNECTED
WiFi IP address: 172.17.1.45 RSSI: -38
NTRIP_CLIENT_WIFI_CONNECTED
Time elapsed: 9 Accuracy: 31 SIV: 21
Batt (87%): Voltage: 4.11V Charging: 1.46%/hr Green
Log file size: 449396 - Generation rate: 2.8kB/s
WIFI_OFF
NTRIP Client connecting to gps-ntrip.ibge.gov.br:2101
NTRIP_CLIENT_ON
NTRIP Client failed to connect to caster. Trying again in 15 seconds.
Time elapsed: 9 Accuracy: 31 SIV: 22
Time elapsed: 16 Accuracy: 31 SIV: 22
Time elapsed: 16 Accuracy: 31 SIV: 22
Time elapsed: 16 Accuracy: 31 SIV: 22
Time elapsed: 17 Accuracy: 31 SIV: 22
Time elapsed: 17 Accuracy: 31 SIV: 22
Time elapsed: 18 Accuracy: 31 SIV: 22
Time elapsed: 18 Accuracy: 31 SIV: 22
Time elapsed: 19 Accuracy: 31 SIV: 22
Batt (87%): Voltage: 4.11V Charging: 1.46%/hr Green
Log file size: 457556 - Generation rate: 1.6kB/s
Time elapsed: 20 Accuracy: 31 SIV: 21
Time elapsed: 20 Accuracy: 31 SIV: 21
Time elapsed: 21 Accuracy: 31 SIV: 21
Time elapsed: 21 Accuracy: 31 SIV: 21
Time elapsed: 22 Accuracy: 31 SIV: 20
Time elapsed: 22 Accuracy: 31 SIV: 20
Time elapsed: 23 Accuracy: 31 SIV: 21
Time elapsed: 23 Accuracy: 31 SIV: 21
Time elapsed: 24 Accuracy: 31 SIV: 22
Time elapsed: 24 Accuracy: 31 SIV: 22
Batt (87%): Voltage: 4.11V Charging: 1.46%/hr Green
Log file size: 466464 - Generation rate: 1.8kB/s
Time elapsed: 25 Accuracy: 31 SIV: 21
Time elapsed: 25 Accuracy: 31 SIV: 21
Time elapsed: 26 Accuracy: 31 SIV: 20
Time elapsed: 26 Accuracy: 31 SIV: 20
Time elapsed: 27 Accuracy: 31 SIV: 22
Time elapsed: 27 Accuracy: 31 SIV: 22
Time elapsed: 28 Accuracy: 31 SIV: 22
Time elapsed: 28 Accuracy: 31 SIV: 22
Time elapsed: 29 Accuracy: 31 SIV: 20
Time elapsed: 29 Accuracy: 31 SIV: 20
Batt (87%): Voltage: 4.11V Charging: 1.46%/hr Green
Log file size: 474081 - Generation rate: 1.5kB/s
Time elapsed: 30 Accuracy: 31 SIV: 21
WIFI_CONNECTING
NTRIP_CLIENT_WIFI_STARTED
Connecting WiFi...
WIFI_CONNECTED
WiFi IP address: 172.17.1.45 RSSI: -40
NTRIP_CLIENT_WIFI_CONNECTED
Time elapsed: 30 Accuracy: 31 SIV: 21
Batt (87%): Voltage: 4.11V Charging: 5.20%/hr Green
Log file size: 483676 - Generation rate: 1.9kB/s
WIFI_OFF
NTRIP Client connecting to gps-ntrip.ibge.gov.br:2101
NTRIP_CLIENT_ON
NTRIP Client failed to connect to caster. Trying again in 30 seconds.
Time elapsed: 36 Accuracy: 31 SIV: 21
Time elapsed: 36 Accuracy: 31 SIV: 21
Time elapsed: 37 Accuracy: 31 SIV: 20
Time elapsed: 37 Accuracy: 31 SIV: 20
Time elapsed: 38 Accuracy: 31 SIV: 22
Time elapsed: 38 Accuracy: 31 SIV: 22
Time elapsed: 39 Accuracy: 31 SIV: 22
Time elapsed: 39 Accuracy: 31 SIV: 22
Time elapsed: 40 Accuracy: 31 SIV: 20
Time elapsed: 40 Accuracy: 31 SIV: 20
Batt (87%): Voltage: 4.11V Charging: 5.20%/hr Green
Log file size: 492122 - Generation rate: 1.7kB/s
Time elapsed: 41 Accuracy: 31 SIV: 21
Time elapsed: 41 Accuracy: 31 SIV: 21
Time elapsed: 42 Accuracy: 31 SIV: 20
Time elapsed: 42 Accuracy: 31 SIV: 20
Time elapsed: 43 Accuracy: 31 SIV: 20
Time elapsed: 43 Accuracy: 31 SIV: 20
Time elapsed: 44 Accuracy: 31 SIV: 20
Time elapsed: 44 Accuracy: 31 SIV: 20
Time elapsed: 45 Accuracy: 31 SIV: 20
Time elapsed: 46 Accuracy: 31 SIV: 20
Batt (87%): Voltage: 4.11V Charging: 5.20%/hr Green
Log file size: 500107 - Generation rate: 1.6kB/s
State: Shut Down, 2023-01-26 13:22:52.654
Log file closed
microSD: Offline

**###TERMINAL COM###**

* What radios are you using: Bluetooth, WiFi, and/or ESP-Now? What app are you using to connect over Bluetooth? Are you transmitting NTRIP back to the device?
In Rover mode: I am using WiFi to connect to NTRIP and receive RTCM.

And in Base mode: I send the RTCM signal by SIK telemetry radio

* Are there any additional details that may help us help you?

Setup:
![Base setup](https://user-images.githubusercontent.com/28196253/214896310-6d6607c2-eb68-40ed-b6b9-5f4877237e3a.jpg)

Rover Mode:
![Rover Mode](https://user-images.githubusercontent.com/28196253/214896393-63cc1c40-acef-47ff-82af-e66e961c0d0a.jpg)

Base Mode:
![Base Mode](https://user-images.githubusercontent.com/28196253/214896415-bd7601df-caaf-4772-88ee-4c0bc239bb40.jpg)

**Comment by nseidle** [comment]
Nice description, photos, and setup. Thanks!

The debug output is superb and very helpful.

I am zeroing in on this section:

> Rover Accuracy (m): 0.2488
Batt (87%): Voltage: 4.11V Charging: 1.87%/hr Green
Log file size: 373340 - Generation rate: 5.5kB/s
Rover Accuracy (m): 0.2381
State: Display Setup, 2023-01-26 13:21:56.469
Batt (87%): Voltage: 4.11V Charging: 1.87%/hr Green
Log file size: 399283 - Generation rate: 5.2kB/s
WiFi IP address: 172.17.1.45 RSSI: -41
State: Base - Not Started, 2023-01-26 13:22:00.573
WIFI_OFF
NTRIP Client connection to caster was broken
NTRIP_CLIENT_ON
*WIFI_OFF
RTCM parser error maxLength: 61 bytes
RTCM parser error maxLength: 71 bytes
RTCM parser error maxLength: 86 bytes
State: Base-Temp - Settle, 2023-01-26 13:22:02.125
Waiting for Horz Accuracy < 0.50 meters: 0.24
Resetting survey
Survey started. This will run until 60 seconds have passed and less than 1.000 meter accuracy is achieved.
State: Base-Temp - Survey Started, 2023-01-26 13:22:08.058
Batt (87%): Voltage: 4.11V Charging: 1.87%/hr Green

Above, the Rover accuracy is 0.2381m. It has not yet achieved RTK fix. So the base will begin a survey-in with ~0.2m accuracy. I recommend waiting for a RTK Fix before starting an assisted survey in for maximum accuracy.

Now, the root of the matter is whether we continue to send NTRIP data to the Base while it's surveying in. 

![image](https://user-images.githubusercontent.com/117102/214902266-3ed5aac3-4b51-46ca-8c59-3f0db8195633.png)
Above: I just ran a test on an RTK Express. The Rover got RTK Fix within a few seconds, then I switched to Base mode. Above is the device re-connecting successfully to the NTRIP Caster. I have a lot of debug statements turned on so don't be surprised by the extra prints.

![image](https://user-images.githubusercontent.com/117102/214903192-5aaf99b9-7d19-4c92-b347-76ab14ebe7f3.png)

Above: A few seconds later, the during survey in, the device disconnects from WiFi. This is not good. I'll look into it. 

![image](https://user-images.githubusercontent.com/117102/214901592-954fdc1f-e621-4a8b-ab4c-dcb27e24dcba.png)
Above: However, my survey-in completed with RTK fix in place and HPA of 0.014m so assuming you enter Survey-In with RTK precision, your survey-in should maintain it for ~30 seconds, and then complete with RTK float. 

We'll figure out why the NTRIP Client is disconnecting during Base Survey-In.

**Comment by eduardobuenof** [comment]
Thanks for the quick response!

Yes, this data I posted was just to explain the issue in which the RTK Express cannot obtain data from the NTRIP client in Base Survey-In mode, the point is this excerpt:

NTRIP Client connecting to gps-ntrip.ibge.gov.br:2101
NTRIP_CLIENT_ON
**NTRIP Client failed to connect to caster**. Trying again in 15 seconds.

But I did tests in an outdoor location with a precision 14mm, but after entering Base Survey-In mode the Wi-Fi is disconnected and can't obtain NTRIP data, and only starts transmission after a minimum 60s, which is time enough that I lost my 14mm accuracy, and sometimes don't start with 14mm, reset to values above 10m.

**Comment by nseidle** [comment]
Ok - I think we have a fix. 

If:

* NTRIP Client is enabled
* Base type is temp
* NTRIP Client is enabled
* Base is started

Then:
* Keep WiFi and NTRIP Client running

Once survey in is complete, NTRIP Client is turned off, and WiFi does whatever WiFi needs to do (stays on for NTRIP Server, etc).

**Comment by nseidle** [comment]
Please give the [release candidate](https://github.com/sparkfun/SparkFun_RTK_Firmware/releases/tag/v3.1RC) a try.

**Comment by eduardobuenof** [comment]
Now I think it's working, but would be somewhere can I see when it pulls data from the NTRIP Client? To make sure it's applying RTCM during Survey-In.

Because in Rover mode it acquired 14mm but during the 60s of the Survey-In preparation it got 26mm HPA.

It is possible to change these ranges:

Menu: Base
1) Toggle Base Mode: Use Survey-In
**2) Set minimum observation time: 60 seconds**
**3) Set required Mean 3D Standard Deviation: 5,000 meters**
**4) Set required initial positional accuracy before Survey-In: 0.100 meters**
6) Toggle NTRIP Server: Disabled
11) Select survey-in radio: Bluetooth
x) Exit

for 2) and 4) I would like to put smaller values
