### ISSUE TITLE
Add Delete Confirmation when deleting commonly used coordinates

### ISSUE THREAD

**Issue by amlago** [sparkfun/SparkFun_RTK_Firmware#391]
¨In the Base Configuration tab, in the list of saved base coordinates, it would be good to also add an option to confirm, when deleting a base, to avoid accidental deletion.¨
#381
This was not contemplated in the latest version of the firmware.

The confirmation to delete files from the SD if it works very well.

_Originally posted by @amlago in https://github.com/sparkfun/SparkFun_RTK_Firmware/issues/381#issuecomment-1416878997_

**Comment by amlago** [comment]
It would also be good if when saving coordinates with the ADD button there would be a saving confirmation notice and/or an overwrite notice if the Base name already exists.

It happened to me that I saved a base by pressing the Add button and I didn't do it because I pressed the button wrong.
It has also happened to me to overwrite a base with the same name.

**Comment by nseidle** [comment]
Right! Sorry I missed that. Should be in soon.
