### ISSUE TITLE
When loading base coordinates from the list, the HAE APC is not updated on the screen

### ISSUE THREAD

**Issue by amlago** [sparkfun/SparkFun_RTK_Firmware#393]
With the last update v3.1 04/02 I have noticed that the HAE Mark and ARP are saved in the base coordinate file. Excellent.

The minor problem is that when loading some base coordinates with the LOAD button, the HAE APC is not updated on the screen at the moment.

I think it does for internal calculations.

**Comment by nseidle** [comment]
Can confirm.

**Comment by nseidle** [comment]
This should be fixed in [v3.2](https://github.com/sparkfun/SparkFun_RTK_Firmware/releases).  Please let us know if this is still a problem.
