### ISSUE TITLE
Allow entry of elevation mask

### ISSUE THREAD

**Issue by amlago** [sparkfun/SparkFun_RTK_Firmware#395]
I would like to enter the angle of the elevation mask.

1) So that, for example, the corrections that are generated are generated only by the satellites above the mask.

2) If the rover is used, the position is only calculated with the satellites above the mask

**Comment by tonycanike** [comment]
Good idea!

**Comment by nseidle** [comment]
Help me understand this. Are you asking for satellites below a certain elevation to not be used in positional fixes?

![image](https://user-images.githubusercontent.com/117102/221271817-45347c2d-5107-4a5d-a992-3c26b8449f2a.png)

We can add a control for the "Minimum elevation for a GNSS satellite to be used in NAV".

Is that what you're looking for?

**Comment by nseidle** [comment]
This is very do-able. Just some work. Please let me know if Min SV Elevation is what you're looking for.

**Comment by amlago** [comment]
What you tell me is correct.
The elevation mask is the minimum angle, above which the satellites are used for the calculations.
If the elevation mask is zero, all visible satellites above the horizon are used.
Generally the angle is 10 degrees or 15 degrees.

**Comment by nseidle** [comment]
Working well. This will be in next RC.

![image](https://user-images.githubusercontent.com/117102/223917237-b0a65ac4-6574-4894-aab9-a92a632a4264.png)

![image](https://user-images.githubusercontent.com/117102/223917306-c1a580d3-7eed-49e0-9ca4-262f6f5c7923.png)

**Comment by nseidle** [comment]
This was implemented in [v3.3 of the RTK firmware](https://github.com/sparkfun/SparkFun_RTK_Firmware/releases/tag/v.3.3). Please let us know if you see any problems.

**Comment by nseidle** [comment]
[Docs added](https://docs.sparkfun.com/SparkFun_RTK_Firmware/configure_gnss/#min-sv-elevation-and-cn0).
