### ISSUE TITLE
portable dynamic model not displayed on menu

### ISSUE THREAD

**Issue by Stefal** [sparkfun/SparkFun_RTK_Firmware#40]
### Subject of the issue
If you select "portable" as dynamic model, it is not displayed on the menu:
![image](https://user-images.githubusercontent.com/8255984/122989309-f136df80-d3a2-11eb-95ee-22bc23dc0580.png)

### Your workbench
* SparkFun RTK Surveyor v1.4-Jun 15 2021

### Steps to reproduce
select portable dynamic model

### Expected behavior
We should see "Set dynamic model: portable"

**Comment by nseidle** [comment]
Thanks for reporting. I can confirm.

**Comment by nseidle** [comment]
Ah, I knew I was forgetting something when I implemented this. The enum starts at 0 and skips 1. I'll fix shortly.

![image](https://user-images.githubusercontent.com/117102/123006511-039a2480-d375-11eb-9ccd-1a56396c711d.png)

**Comment by nseidle** [comment]
New binaries are in [the release](https://github.com/sparkfun/SparkFun_RTK_Firmware/releases/tag/v1.4). Please keep the issues coming!
