### ISSUE TITLE
Battery icon at the start of AP Config

### ISSUE THREAD

**Issue by amlago** [sparkfun/SparkFun_RTK_Firmware#414]
Battery icon at the start of AP Config

I would like to see the battery charge value with a battery icon on the AP config page.
It could be put at the beginning below the Sparkfun logo.

**Comment by tonycanike** [comment]
I like this idea. 

Could it include external power connected status?  I have a need to know external power is connected when the battery is fully charged.  

The battery LED on the front panel goes dark when the battery is fully charge whether or not there is external power connected.  


See

https://github.com/sparkfun/SparkFun_RTK_Facet/issues/9

**Comment by nseidle** [comment]
These are great ideas. I'm not certain we can detect external power or not but we'll try.

**Comment by amlago** [comment]
In the serial configuration, the battery status is shown and if it is charging or discharging.
I think that information would be more than enough if it was placed under the initial Sparkfun icon with an icon next to it.

**Comment by nseidle** [comment]
That's what we're leveraging. The problem is that the fuel gauge IC is very slow to respond. It can takes multiple minutes to switch from an indication of discharging to charging at near 100% capacity. We'll get something implemented.

**Comment by nseidle** [comment]
Here's the basic implementation:

![image](https://user-images.githubusercontent.com/117102/222787223-14ff509a-0df8-4a3e-a6b7-b647e02494d9.png)

There's still some alignment, and the icon may move eventually, but it works. Icon is green if charging. '+97%' is charging, whereas '97%' is discharging.

**Comment by nseidle** [comment]
Also, battery level is updated dynamically every second. As noted previously, the system can take a few minutes to recognize the transition from discharging to charging.

**Comment by amlago** [comment]
You really do a spectacular job.
Excellent

**Comment by nseidle** [comment]
> You really do a spectacular job.

Thank you! That makes my Friday :)

**Comment by nseidle** [comment]
This is added in [v3.2](https://github.com/sparkfun/SparkFun_RTK_Firmware/releases).
