### ISSUE TITLE
SD icon does not appear on screen V3.2

### ISSUE THREAD

**Issue by amlago** [sparkfun/SparkFun_RTK_Firmware#415]
SD icon does not appear on screen V3.2

With version 3.2 the SD icon disappeared from the screen, even though the log file is still being generated.
In their place are the classic moving vertical bars.

**Comment by nseidle** [comment]
Interesting. This was similarly reported on the forum: https://forum.sparkfun.com/viewtopic.php?f=116&t=59141

Thanks as always for reporting! I'll work on a fix.

**Comment by nseidle** [comment]
I believe we have this fixed. Please give the RC a try and let me know if you see anything else.

**Comment by nseidle** [comment]
This should be fixed in [v3.2](https://github.com/sparkfun/SparkFun_RTK_Firmware/releases). Please let us know if this is still a problem.
