### ISSUE TITLE
no NMEA output on Bluetooth with ESP32 Thing Plus C

### ISSUE THREAD

**Issue by edgecase14** [sparkfun/SparkFun_RTK_Firmware#426]
### Subject of the issue
Previously using an Ardusimple ESP32-WROOM-32D, and various Sparkfun firmware versions, it is working.  The SparkFun ESP32-WROOM-32E appears to function, GPS fix with LL is shown in System config menu, the +++ bluetooth redirect works, from Android etc. but no NMEA sentences.  The default sentences or configuring a few extra GSA GLL etc doesn't make a difference.

### Your workbench
The ESP32 Thing Plus C connected via QWIIC to ZED-F9P NEO-D9C Combo breakout board.
Firmware 3.2 from SparkFun_RTK_Firmware_Binaries. using default first-flash configuration.  I tried the Ardusimple D9S + F9P boards, and they don't work either.

The Ardusimple ESP32 has a config file already, but I don't want to risk wiping it out.  It would be great if i could make a backup and reset to detaults.  It was connected via I2C.

### Steps to reproduce
The Ardusimple was running with 3.1 RC Jan 26.  I upgraded it to v3.2 release, and it still works.

### Expected behavior
It should function the same with the added bonus of Fuel Gauge.

### Actual behavior
Everything seems the same but no NMEA output via Bluetooth.

USB serial console output after reset, Sparkfun ESP32 Thing Plus C:

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1240
load:0x40078000,len:13012
load:0x40080400,len:3648
entry 0x400805f8
Display not detected
ZED-F9P firmware: HPG 1.32
LittleFS Started
SparkFun RTK Surveyor v3.2-Mar  8 2023
settingsFile not found in LittleFS
settingsFile not found in LittleFS
settingsFile not found in LittleFS
settingsFile not found in LittleFS
settingsFile not found in LittleFS
settingsFile not found in LittleFS
settingsFile not found in LittleFS
Profile 'Profile1' loaded
MAX17048 configuration complete
Batt (2%): Voltage: 3.65V Charging: 2.50%/hr Red
GNSS configuration complete
System time set to: Wednesday, March 15 2023 11:33:28
State: Rover - Not Started, 2023-03-15 11:33:29.706
Batt (2%): Voltage: 3.65V Charging: 2.91%/hr Red
*WIFI_OFF
Bluetooth broadcasting as: Surveyor Rover-5312
*NTRIP_CLIENT_OFF
State: Rover - No Fix, 2023-03-15 11:33:30.817
State: Rover - Fix, 2023-03-15 11:33:30.829
Batt (2%): Voltage: 3.65V Charging: 3.33%/hr Red
Batt (2%): Voltage: 3.65V Charging: 3.33%/hr Red
Batt (2%): Voltage: 3.65V Charging: 3.95%/hr Red
Batt (2%): Voltage: 3.65V Charging: 3.95%/hr Red
BT client Connected
Echoing all serial to BT device
SparkFun RTK Surveyor v3.2-Mar  8 2023
** Bluetooth broadcasting as: Surveyor Rover-5312 **
Menu: Main
1) Configure GNSS Receiver
2) Configure GNSS Messages
3) Configure Base
4) Configure Ports
5) Configure Logging

6) Configure WiFi
p) Configure User Profiles
r) Configure Radios
P) Configure PointPerfect
s) Configure System
f) Firmware upgrade
b) Exit Bluetooth Echo mode
x) Exit
b

**Comment by nseidle** [comment]
Hi @edgecase14,

Sorry for the slow reply! I had read your issue but couldn't think of why it would be failing, so I had to back burner my response.

Thank you very much for returning to report the solution. Glad to hear you're running.

Let us know if you need anything else.
