### ISSUE TITLE
GNSS configuration menu gives no information that Base measurement rate is fixed at 1Hz

### ISSUE THREAD

**Issue by tonycanike** [sparkfun/SparkFun_RTK_Firmware#427]
### Subject of the issue
WiFi GNSS menu gives no information that the base measurement rate is fixed at 1Hz despite the the user setting the measurement rate. This could confuse users who are trying to customize the message rates to specific intervals.

UI should make it clear to the users that the base measurement rate is fixed at 1Hz.   A few words in  a tool-tip would suffice.

### Your workbench
v3.3  11-Mar-2023

### Steps to reproduce
Taking @nseidle 's word for it.
https://github.com/sparkfun/SparkFun_RTK_Firmware/issues/422#issuecomment-1464488632

Taking the documentation's word for it.
https://docs.sparkfun.com/SparkFun_RTK_Firmware/configure_gnss/

### Expected behavior
The WiFi configuration page should document that the measurement rate for a base is fixed at 1Hz.    This could be stated in the ToolTip.
I haven't checked the serial menu but it should also be clear about the fixed base measurement rate.

**Comment by nseidle** [comment]
Agreed. Added:

![image](https://user-images.githubusercontent.com/117102/231277143-ce7018c1-dcc3-4a64-84f1-115fcf9209d7.png)

![image](https://user-images.githubusercontent.com/117102/231277254-30f574c5-cac6-4d7c-80a2-4b7c204cc2ac.png)
