### ISSUE TITLE
V3.3 Battery icon looks sketchy in wifi settings

### ISSUE THREAD

**Issue by amlago** [sparkfun/SparkFun_RTK_Firmware#430]
V3.3 Battery icon looks sketchy in wifi settings

In version 3.3 the battery icon is incomplete on the cell phone screen in wifi settings

**Comment by nseidle** [comment]
Agreed. Should be fixed in the RC shortly:

![image](https://user-images.githubusercontent.com/117102/231261467-98a72193-3b7e-4515-a8bb-a8e1d8345273.png)

**Comment by nseidle** [comment]
This should be fixed in [v3.3 of the RTK firmware](https://github.com/sparkfun/SparkFun_RTK_Firmware/releases/tag/v.3.3). Please let us know if you still see problems.
