### ISSUE TITLE
Write today's date to log file in $GNTXT message at startup

### ISSUE THREAD

**Issue by tonycanike** [sparkfun/SparkFun_RTK_Firmware#440]
### Subject of the issue

Sometimes multiple days of log data get written to a file called "SFE" and I need to figure out which day's data are in the SFE file.

The NMEA messages give the time, but not the date.

It's really really hard to cut up a file using Notepad++ or some other text editor if we don't know where each day's data are

It would also be useful to know the logging actually worked, and having the $GNTXT message with today's date would be helpful.

Yes, ideally everything would work and this wouldn't be necessary.  But it does get frustrating being a beta-tester so help us out a little!

Thanks.

Facet running v3.3-Mar 11 2023.  I had to downgrade to 3.2 release due to wifi config issues so don't remember for sure.

**Comment by nseidle** [comment]
> Sometimes multiple days of log data get written to a file called "SFE"

There is a log on your SD card called "SFE.ubx"? That's a rather large issue that we would need to fix. Or are you seeing a mixing of data between log files, aka issue #401?

> Yes, ideally everything would work and this wouldn't be necessary. But it does get frustrating being a beta-tester so help us out a little!

Ah. That's very fair. I'll get after it.

**Comment by nseidle** [comment]
![image](https://user-images.githubusercontent.com/117102/234105860-e41e3818-8a35-420d-a754-8bdced99403b.png)

Date format is: YYMMDD,HHMMSS

**Comment by tonycanike** [comment]
Thank you!  Awesome!

**Comment by nseidle** [comment]
This was implemented in [v3.3 of the RTK firmware](https://github.com/sparkfun/SparkFun_RTK_Firmware/releases/tag/v.3.3). Please let us know if you see any problems.
