### ISSUE TITLE
Reset to Factory Defaults - Warn SD card will be formatted (or clarify it's not the SD card.)

### ISSUE THREAD

**Issue by tonycanike** [sparkfun/SparkFun_RTK_Firmware#441]
Facet running v3.3-Mar 11 2023  and 3.2 release

When resetting to factory defaults there is a "are you sure" confirmation, but there's no warning (reminder) that the SD card will be reformatted.   Sad :( when I forget that part.

Oh huh....it said it reformatted the SD card but it didn't.  Or maybe the message wasn't specifically about the SD card and I misunderstood?  Was the message "formatting the file system"?  Did it only format the little internal file system??     Anyway its a very scary message when there's no warning!

**Comment by nseidle** [comment]
Sorry for the confusion. A factory reset does the following:

* Erase/format the *internal* file system (this is LittleFS, and is used if no SD is detected)
* Sets the ZED-F9x to factory defaults (baud rate, I2C address, update rate, etc)
* If an SD card is detected, remove the setting file, and ECEF/Geo coordsinate files associated with the current profile.

It does not format or touch previously logged data on the SD card. 

I'll update the serial print message to "Formatting internal file system..." to clarify.

**Comment by tonycanike** [comment]
Thanks, appreciate the quick response!
