### ISSUE TITLE
ROVER: Decode RCTM 1005,1006,1007 and record in $GNTXT messages to rover log file

### ISSUE THREAD

**Issue by tonycanike** [sparkfun/SparkFun_RTK_Firmware#447]
### Subject of the issue
New Feature Request: The rover decodes the  RTCM 1005,1006,1007 messages received from the base and records the base coordinates in $GNTXT messages in the rover log file.

This would allow users to look at the Rover's log file and easily know the base coordinates used for the Rover data.   Today (3.3-dev March) it's a bit of a process on the base end to document the base coordinates.   You might let the base survey itself in, and then switch to wifi config and copy the zed coordinates to a saved location, or screen-shot the wifi config page.  And then you need to exit WiFi and restart the base without restarting survey-in or else the coordinates you saved will not be the coordinates the base actually used.

We need to know where the base was when we process the rover data, so the rover log file is also a logical place to put it.  If the base location was in the Rover file, we might not need to look at the base log file.  That saves a fair bit of fussing with the base log and resultant files, text editors, and mini-SD cards that are pretty small to handle.  One less opportunity for errors, like forgetting the mini SD card in the computer in the office.

Alternatively,  putting the RTCM 1005,1006,1007 in the rover log files and providing/recommending/documenting a decoder to read the rover log file and display the RTCM messages in plain text would be a useful and usable alternative.

Split out from #405 so there's only one request per submitted issue.

**Comment by PaulZC** [comment]
Hi Tony (@tonycanike ),

I've upgraded the u-blox library (v3.0.12). It is now able to parse the correction data being 'pushed' to the u-blox module. It is able to parse 1005 and 1006, allowing the ARP ECEF and height to be extracted. Now we have this, it should be a piece of cake to copy the ARP into a new Rover GNTXT message.

**Question:** how essential is 1007? If I'm reading it right, it contains the name (description) of the antenna - but not its location?

Thanks - and best wishes,
Paul

**Comment by tonycanike** [comment]
Paul, awesome news!  1007 isn't critical to me at all. Thanks for all the hard work - these things really help!

Tony.

**Comment by PaulZC** [comment]
Just a quick update that this feature is working well in the "Reference Station Ethernet" version of the release candidate. It won't be long until it is merged into release-candidate proper.

The u-blox library integrity checker can now also print the content of any GNTXT messages it finds:

https://github.com/sparkfun/SparkFun_u-blox_GNSS_v3/blob/main/Utils/UBX_Integrity_Checker.py

**Comment by tonycanike** [comment]
Great news, thanks!

**Comment by PaulZC** [comment]
This feature in the latest release_candidate binary.

Open the Logging Menu, and select option 5 ("5) Log Antenna Reference Position from RTCM 1005/1006: ") to enable. Option 6 sets the logging interval.

The ARP is logged in a custom GNTXT,01,01,10 message as ECEF-X, ECEF-Y, ECEF-Z, Antenna Height. The Antenna Height will be zero if the data was extracted from 1005.

The latest version of the integrity checker will print the GNTXT messages if you ask it to. See https://github.com/sparkfun/SparkFun_RTK_Firmware/issues/476#issuecomment-1567346348.

Enjoy!
Paul

**Comment by nseidle** [comment]
This has been implemented in v3.4. Docs are [here](https://docs.sparkfun.com/SparkFun_RTK_Firmware/configure_data_logging/#serial-interface).
