### ISSUE TITLE
boot and partition info is duplicated and not part of CI

### ISSUE THREAD

**Issue by gdt** [sparkfun/SparkFun_RTK_Firmware#452]
While debugging a problem (new esptool and RTK_Surveyor do not getalong, #451) , I found multiple copies of the bootloader and partition code:

```
./SparkFun_RTK_Firmware_Binaries/bin/boot_app0.bin
./SparkFun_RTK_Firmware_Binaries/bin/RTK_Surveyor.ino.bootloader.bin
./SparkFun_RTK_Firmware_Binaries/bin/RTK_Surveyor_Partitions_4MB.bin
./SparkFun_RTK_Firmware_Binaries/bin/RTK_Surveyor_Partitions_16MB.bin
./SparkFun_RTK_Firmware_Uploader/RTK_Firmware_Uploader/resource/boot_app0.bin
./SparkFun_RTK_Firmware_Uploader/RTK_Firmware_Uploader/resource/RTK_Surveyor.ino.bootloader.bin
./SparkFun_RTK_Firmware_Uploader/RTK_Firmware_Uploader/resource/RTK_Surveyor_Partitions_4MB.bin
./SparkFun_RTK_Firmware_Uploader/RTK_Firmware_Uploader/resource/RTK_Surveyor_Partitions_16MB.bin
```

Ideally, there would only be one copy.  But really, these are, I think, binaries built as part of the firmware build process, and thus there would be no copies in git, and the build artifacts would have not only firmware, but the .bin files.

(I realize this is the software engineering view, and perhaps not the firmware world view.)

**Comment by nseidle** [comment]
Partition files removed from [SparkFun_RTK_Firmware_Binaries](https://github.com/sparkfun/SparkFun_RTK_Firmware_Binaries) repo.
