### ISSUE TITLE
3.3 has wrong tag

### ISSUE THREAD

**Issue by gdt** [sparkfun/SparkFun_RTK_Firmware#457]
Following parallel structure from before, it should be `v3.3`, not `v.3.3`.
```
v.3.3
v3.0
v3.1
v3.1RC
v3.2
v3.2RC
v3.3RC
```

**Comment by gdt** [comment]
(and not really on topic, but v.3.3 binary updated fine on my RTK Express, and on boot it did NTRIP and went into RTK FIX while indoors, so looks good!)

**Comment by nseidle** [comment]
Dah! Good catch. Fixed.

![image](https://user-images.githubusercontent.com/117102/236593199-b40e6fee-3c22-47e0-bdce-8ce58f36bb0d.png)
