### ISSUE TITLE
firmware update from v3.2 to 3.3 via console fails - custom ESP32 Thing Plus C device

### ISSUE THREAD

**Issue by edgecase14** [sparkfun/SparkFun_RTK_Firmware#460]
### Subject of the issue
Attempting firmware update from v3.2 with custom ESP32 Thing Plus C + F9P-D9S combo board, appears to work, but aborts and reboots.

### Your workbench
* What version of RTK firmware are you running? v3.2 binary from Github
* What radios are you using: Bluetooth, WiFi,
*  What app are you using to connect over Bluetooth? none
* Are you transmitting NTRIP back to the device? No
* Are there any additional details that may help us help you?

### Steps to reproduce
* configure 1 wifi client SSID
* attempt upgrade via console
* console output:

Menu: Update Firmware
Current firmware: v3.2
c) Check SparkFun for device firmware
e) Allow Beta Firmware: Disabled
x) Exit
c
Connecting WiFi... 
WiFi IP address: 192.168.3.109 RSSI: -54
Current firmware version: v3.2
Checking to see if an update is available from https://raw.githubusercontent.com/sparkfun/SparkFun_RTK_Firmware_Binaries/main/RTK-Firmware.json

Menu: Update Firmware
Current firmware: v3.2
e) Allow Beta Firmware: Disabled
u) Update to new firmware: v3.3
x) Exit
u
Installing new firmware

[ 0%
abort() was called at PC 0x4008274e on core 1

Backtrace:0x40083e15:0x3ffd06d00x400958e9:0x3ffd06f0 0x4009b6c5:0x3ffd0710 0x4008274e:0x3ffd0790 0x4012abcf:0x3ffd07e0 0x40116855:0x3ffd0800 0x40102ece:0x3ffd0820 0x40103075:0x3ffd0840 0x400d61e2:0x3ffd0870 0x40 

ELF file SHA256: 0000000000000000

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1240
load:0x40078000,len:13012
load:0x40080400,len:3648
entry 0x400805f8
Display not detected
ZED-F9P firmware: HPG 1.32
LittleFS Started
SparkFun RTK Surveyor v3.2-Mar  8 2023
Reset reason: ESP_RST_PANIC
settingsFile not found in LittleFS

### Expected behavior
new firmware should be flashed

### Actual behavior
device reboots, continues to run old firmware successfully

**Comment by nseidle** [comment]
Thanks for reporting! (And always reminding me you're on custom hardware). Update is working for me.

![image](https://github.com/sparkfun/SparkFun_RTK_Firmware/assets/117102/60516d3b-6553-4f3a-9dc4-3e0eef859300)

Please make sure your partitions are set correctly. I suspect you are using a different partition setup from the compiled binaries causing the update to fail. See [docs here](https://docs.sparkfun.com/SparkFun_RTK_Firmware/firmware_update/#compiling-source). Specifically, replace your partition table with the [app3M_fat9M_16MB,csv](https://github.com/sparkfun/SparkFun_RTK_Firmware/blob/main/Firmware/app3M_fat9M_16MB.csv).
