### ISSUE TITLE
Configuration menu

### ISSUE THREAD

**Issue by Eric-FR** [sparkfun/SparkFun_RTK_Firmware#50]
With the Express and the Firmware_v15RC-July23.bin, we have access to the menu through the Setup button. When going down, there is a Configuration entry. When selecting it, the screen is just switching off but the receiver is still running. If pressing Setup again, the screen switch on and menu appears again, to mark a waypoint for instance, but then switch off again. By using Base or Rover options, the screen switch on and stay on.

So, I don't know for is the configuration menu, but for sure, it don't behave as expected.

**Comment by nseidle** [comment]
Indeed. It's currently WIP.

**Comment by nseidle** [comment]
Closing - the [WiFi AP](https://github.com/sparkfun/SparkFun_RTK_Firmware/issues/51) is now available.
