### ISSUE TITLE
Add firmware auto-update

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Firmware#501]
Provide a method for users to opt-in to automatic firmware checking and updates.

**Comment by amlago** [comment]
Hello, I really don't know if I want the device to update automatically.
I like to control the version I'm using.
But some people may be interested.
If it is possible to enable and disable the option may work.

**Comment by nseidle** [comment]
Closing for now as not needed. We may re-visit someday.
