### ISSUE TITLE
Default profiles with Wifi configuration

### ISSUE THREAD

**Issue by Eric-FR** [sparkfun/SparkFun_RTK_Firmware#56]
When using serial configuration, in the Configure GNSS Messages part, we have two options:
7) Reset to Surveying Defaults (NMEAx5)
8) Reset to PPP Logging Defaults (NMEAx5 + RXMx2)

It would be nice to have same options when using Wifi configuration.

**Comment by nseidle** [comment]
Agreed. I'll work it into v1.6.

**Comment by nseidle** [comment]
Added in v1.7.
