### ISSUE TITLE
Display icon according to dynamic

### ISSUE THREAD

**Issue by Eric-FR** [sparkfun/SparkFun_RTK_Firmware#57]
In rover mode, display an icon corresponding to the dynamic mode selected instead of the present car

Some ideas:

1) Portable : gnss antenna?
2) Stationary : a tripod
3) Pedestrian : a walking guy
4) Automotive : a car (the present icon)
5) Sea : a boat
6) Airborne 1g : an horizontal plane
7) Airborne 2g : a plane going up at 45°
8) Airborne 4g : a plane going up verticaly
9) Wrist : a watch?
10) Bike : a bicycle

;-)

**Comment by nseidle** [comment]
I really like this idea. My only concern is the default (portable = GNSS antenna) may be too alien to most users. 

Hmm, it's growing on me. I'll see what I can do.

**Comment by Eric-FR** [comment]
Portable (default) : Applications with low acceleration, e.g. portable devices. Suitable for most situations.

Icon : a device/smartphone handle in a hand? a gnns antenna handle by a hand?

For sea, add waves under the boat. It is supposed to be at 0 m level, in the sea, not in a lake.

**Comment by pyrog** [comment]
> For sea, add waves under the boat. It is supposed to be at 0 m level, in the sea, not in a lake.

Really?
Maybe just elevation is ~ constant?

**Comment by Eric-FR** [comment]
At sea: Recommended for applications at sea, with zero vertical velocity. Zero vertical velocity assumed. Sea level assumed.

**Comment by nseidle** [comment]
Ok gents, how good is your pixel art? I need your help coming up with some rough bitmaps for each of these.  Size requirements: Must be equal to or smaller than 15 pixels wide, 12 pixels tall. I've attached my [DynamicModel-Stationary-Example.zip](https://github.com/sparkfun/SparkFun_RTK_Firmware/files/7268559/DynamicModel-Stationary-Example.zip) as an example.

**Comment by nseidle** [comment]
These have been implemented in v18RC so you can see what they look like.

**Comment by nseidle** [comment]
If anyone has better graphics, please let me know!
