### ISSUE TITLE
Write speed: nankB/s during WIFI config

### ISSUE THREAD

**Issue by pyrog** [sparkfun/SparkFun_RTK_Firmware#59]
### Subject of the issue
```
State: WiFi Config
Batt (93%): Voltage: 4.20V Charging: 22.46%/hr Green

UBX file size: 182511 - Generation rate: 0.0kB/s - Write speed: nankB/s
Batt (93%): Voltage: 4.20V Charging: 22.46%/hr Green
```

### Your workbench
* RTK_Surveyor_Firmware_v16.bin

### Steps to reproduce
* Enter WIFI config during USB connexion

### Expected behavior
Don't display UBX file status or display a 0 Write speed
`UBX file size: 182511 - Generation rate: 0.0kB/s - Write speed: 0.0kB/s`

**Comment by nseidle** [comment]
I think I've got a fix in place. Please re-open if the latest v1.8RC doesn't fix this.
