### ISSUE TITLE
NTRIP Client Connection to Caster was broken

### ISSUE THREAD

**Issue by YashuSystems** [sparkfun/SparkFun_RTK_Firmware#643]
I am seeing where the Facet NTRIP Client connection to rtk2go.com caster is periodically lost in FW v3.6.

Everything worked acceptably in v3.6RC.

Connection is lost across either WiFi or SW Maps IOS w/ BLE.

FW v3.7 also still has the same issue.

GGA messages to caster are disabled. If I enable them, connection is lost immediately in v3.6 and v3.7

Can you advise if this issue can be reproduced @ sparkfun?

v3.6RC
![NTRIP_Client_Connection_Fine_v3 6RC](https://github.com/sparkfun/SparkFun_RTK_Firmware/assets/111541055/d405870f-e3dc-4e97-879b-069d26f7f41e)

v3.6
![NTRIP_Client_Connection_to-Caster_was_broken_v3 6](https://github.com/sparkfun/SparkFun_RTK_Firmware/assets/111541055/9304a0af-0518-4ea4-95de-86cb5610f3e6)

**Comment by nseidle** [comment]
Yep, I just hit this as well. We'll get it looked at.

**Comment by nseidle** [comment]
We believe we have this is fixed in [v3.8](https://github.com/sparkfun/SparkFun_RTK_Firmware/releases). Please let us know if you continue to see any other problems.

**Comment by skyviewaerials** [comment]
Hello Nathan,I’ve been trying to download v3.8 but web connection closes before the firmware is downloaded?Thanks for your help,Mike Sent from my iPhoneOn Sep 19, 2023, at 9:43 AM, Nathan Seidle ***@***.***> wrote:﻿
Closed #643 as completed.

**Comment by skyviewaerials** [comment]
Hello Nathan,I’ve tried to update the firmware with the web connection and the serial connection, the same thing happened with both, the unit reboots before the file is downloaded.Could I get a link to the firmware to push it to the unit?Thanks for all your help,Mike Sent from my iPhoneOn Sep 19, 2023, at 9:58 AM, Michael Germana ***@***.***> wrote:﻿Hello Nathan,I’ve been trying to download v3.8 but web connection closes before the firmware is downloaded?Thanks for your help,Mike Sent from my iPhoneOn Sep 19, 2023, at 9:43 AM, Nathan Seidle ***@***.***> wrote:﻿
Closed #643 as completed.

**Comment by skyviewaerials** [comment]
Hello Nathan,
I was able to download the d3.8 and used it as a base without issue, although I do see a lot of extra data, is there any way to limit some of it, I tried turning off some items in the debugging panel. Tomorrow I will try a rover test.
Thanks,
Mike
