### ISSUE TITLE
line too small in NVM.ino loadSystemSettingsFromFileSD

### ISSUE THREAD

**Issue by PaulZC** [sparkfun/SparkFun_RTK_Firmware#645]
I noticed ```Settings line 61 too long``` errors after manually entering a PP device profile token.

[This line of code](https://github.com/sparkfun/SparkFun_RTK_Firmware/blob/fc7598450f095656730da18026eb70a95ceb1a97/Firmware/RTK_Surveyor/NVM.ino#L462) defines ```line``` to be 60 characters. But the line containing the ```pointPerfectDeviceProfileToken``` can be 68 characters - excluding the terminator. The 60 needs to be increased to (at least) 70. 100 might be a better choice to match ```parseLine```.

Ditto for [this line](https://github.com/sparkfun/SparkFun_RTK_Firmware/blob/fc7598450f095656730da18026eb70a95ceb1a97/Firmware/RTK_Surveyor/NVM.ino#L519)

**Comment by nseidle** [comment]
This has been fixed in v3.9.
