### ISSUE TITLE
Doubt about the maximum number of Facet channels.

### ISSUE THREAD

**Issue by amlago** [sparkfun/SparkFun_RTK_Firmware#669]
Facet v3.8
Using the u-center I see what appears to be a maximum of 60 channels in use.
The zed-f9p is supposed to have just over 180 available channels.
Can someone explain to me what causes this difference?
I add screenshots of the u-center.
greetings

**Comment by amlago** [comment]
Image
![canales facet-2](https://github.com/sparkfun/SparkFun_RTK_Firmware/assets/53310328/05377269-3dad-4c80-86f3-1a77e29ca3af)

**Comment by amlago** [comment]
![canales facet](https://github.com/sparkfun/SparkFun_RTK_Firmware/assets/53310328/d43fc382-bd20-4b45-b3b2-e397542fc17a)

**Comment by nseidle** [comment]
Interesting question. I brought it up with u-blox: 

"The listed channels assignment in your ubx-cfg-gnss is used for M8 and before and are for L1 only band. For the F9/M10/F10 products the “Gen 9 configuration” should be used, and in that window you no longer have the ability/need to set tracking channels as the firmware will dynamically assign based on the current number of SV deployed, but with 184 channel, it will never be an issue."

It sounds to me like it's not a concern.

Thanks for asking!
