### ISSUE TITLE
Feature request : generate UBX-TIM-TM2 message when marking waypoint

### ISSUE THREAD

**Issue by Eric-FR** [sparkfun/SparkFun_RTK_Firmware#69]
Right now, when marking a waypoint (with the Express), only a corresponding NMEA sentence is generated.

When recording RAWX data and doing post-processing with RTKLib, it is not possible to extract waypoints. Indeed, when a waypoint is marked using the INT pin of the F9P, a UBX-TIM-TM2 sentence is generated. RTKLib is able to read it and provide, after post-processing, a separate .pos file for waypoints. Having the same possibility with the Express would be welcome.

**Comment by nseidle** [comment]
There is not a software command to trigger the ZED to generate a TM2 message. The only way to do it is with the INT pin which is accessible via the [external triggers](https://github.com/sparkfun/SparkFun_RTK_Firmware/issues/72). To get the functionality you want you could rig up an external button: every time the button is pressed, the TM2 message would be recorded to the log. An external button is probably not ideal but it should work.

Ideally, you could do this from the 'Mark' method through the graphic menu (pressing **SETUP**) but I cannot think of a way to do this via software... I would have to rev the hardware and connect an ESP32 GPIO to the INT pin. I wish I would have done this, but hindsight is always 20/20. For now, the Data port is your best bet.
