### ISSUE TITLE
High power consumption of BT connexion

### ISSUE THREAD

**Issue by Eric-FR** [sparkfun/SparkFun_RTK_Firmware#70]
RTK Express
Firmware v1.8

I made static measurements on my balcony with the u-blox antenna at fix position. I started with fully charged battery and let the Express running until the battery is empty. 

With BT connexion to my smartphone (Lefebure NTrip client) with centipede network. to local base station. Two runs:
5h04 (256 mA, assuming 1300 mAh for the internal battery) 
5h01 (259 mA)

Without BT connexion:
7h13 (180 mA)
7h04 (184 mA)

So, the overhead of BT connexion is 75 mA (+41%).

I made similar measurements with F9P_RAWX_Logger.
logger alone : 163 mA
logger with hc-05 (on F9P uart2)  with BT connexion : 208 mA

This is significantly lower, with only 45 mA of overhead, including the powering of hc-05 itself.

**Comment by nseidle** [comment]
Hi Eric - thank you for the tests! And confirming 'in-the-field' current numbers.

You measured Paul's [F9P_RAWX_Logger](https://github.com/PaulZC/F9P_RAWX_Logger) that uses the Adafruit SAMD21 based board? I am not surprised it was lower current :) The ESP32 is a bit more power hungry. Additionally, the HC-05 is very much tuned for current reduction. But using these components we will lose all system configuration options including but not limited to [WiFi config](https://learn.sparkfun.com/tutorials/sparkfun-rtk-express-hookup-guide#system-configuration---wifi).

We are going to stick with the current ESP32 for WiFi+BLE for now. If you need more power in the field you should be able to use any [USB power bank](https://www.sparkfun.com/products/15593).
