### ISSUE TITLE
New Feature Request: Configuration utility setting that sets UBLOX_CFG_USBINPROT_SPARTN to 1 on reboot/powerup

### ISSUE THREAD

**Issue by demurs73582** [sparkfun/SparkFun_RTK_Firmware#713]
### Subject of the issue
Background at issue 497. [https://github.com/sparkfun/SparkFun_RTK_Firmware/issues/497] 

Would be value-adding to have a new feature in the configuration utility that will set UBLOX_CFG_USBINPROT_SPARTN to 1 on reboot/powerup or at least leaves it alone if already set to 1. This will allow getting a PointPerfect SPARTN data feed to the Facet from GNSS Master over a USB cable, without having to use u-center after each reboot/powerup.

### Your workbench
* RTK firmware 3.9
* What radios are you using: none - USB OTG cable from Facet to Android phone
* Are there any additional details that may help us help you? ZED-F9P firmware version 1.32

### Steps to reproduce
reboot or powerup the Facet - the ZED-F9P setting for CFG-USBINPROT-SPARTN gets overwritten to 0, needs to be 1 to get PointPerfect SPARTN feed over USB cable.

### Expected behavior
The configuration utility would provide a setting where either the existing CFG-USBINPROT-SPARTN setting is not overwritten or is set to 1

### Actual behavior
see "steps to reproduce"

**Comment by nseidle** [comment]
This has been fixed in [v3.10](https://github.com/sparkfun/SparkFun_RTK_Firmware/releases/tag/v3.10). Closing issue.
