### ISSUE TITLE
SD Init Failed message when Bluetooth is connected

### ISSUE THREAD

**Issue by Stefal** [sparkfun/SparkFun_RTK_Firmware#758]
### Subject of the issue
As soon as the Facet is bluetooth connected, there are a lot of `sd init failed` message when you read the serial output

### Your workbench
* RTK Facet
* Firmware v4.0
* No SD card inserted

### Steps to reproduce

Connect a terminal on the Usb serial output, wait a few seconds, then connect a android phone with the Facet via a Ntrip Client.
```
Batt (67%): Voltage: 4.02V Charging: 28.70%/hr Green
Rover Accuracy (m): 1.0526, SIV: 17
Rover Accuracy (m): 1.0505, SIV: 17
Rover Accuracy (m): 1.0482, SIV: 17
Batt (67%): Voltage: 4.02V Charging: 28.70%/hr Green
Rover Accuracy (m): 1.0406, SIV: 18
Rover Accuracy (m): 1.0310, SIV: 18
Batt (67%): Voltage: 4.02V Charging: 28.70%/hr Green
Rover Accuracy (m): 1.0222, SIV: 18
Rover Accuracy (m): 1.0157, SIV: 18
Rover Accuracy (m): 1.0103, SIV: 18
Batt (67%): Voltage: 4.02V Charging: 24.34%/hr Green
Rover Accuracy (m): 1.0064, SIV: 18
Rover Accuracy (m): 1.0025, SIV: 18
Batt (67%): Voltage: 4.02V Charging: 24.34%/hr Green
Rover Accuracy (m): 1.0001, SIV: 18
Rover Accuracy (m): 0.9993, SIV: 18
Rover Accuracy (m): 0.9980, SIV: 18
Batt (67%): Voltage: 4.02V Charging: 24.34%/hr Green
BT client Connected
Rover Accuracy (m): 0.9967, SIV: 19
SD init failed - using SPI and SdFat. Is card formatted?
SD init failed - using SPI and SdFat. Is card formatted?
Rover Accuracy (m): 0.9886, SIV: 19
SD init failed - using SPI and SdFat. Is card formatted?
Batt (67%): Voltage: 4.02V Charging: 24.34%/hr Green
SD init failed - using SPI and SdFat. Is card formatted?
Rover Accuracy (m): 0.9803, SIV: 19
SD init failed - using SPI and SdFat. Is card formatted?
SD init failed - using SPI and SdFat. Is card formatted?
Rover Accuracy (m): 1.9232, SIV: 19
STATE_ROVER_FIX --> STATE_ROVER_RTK_FLOAT, 2024-03-14 13:55:15.070
SD init failed - using SPI and SdFat. Is card formatted?
Rover Accuracy (m): 0.5185, SIV: 19
Batt (67%): Voltage: 4.02V Charging: 24.34%/hr Green
SD init failed - using SPI and SdFat. Is card formatted?
Rover Accuracy (m): 0.3321, SIV: 19
SD init failed - using SPI and SdFat. Is card formatted?
BT client disconnected
Rover Accuracy (m): 0.2890, SIV: 19
Batt (68%): Voltage: 4.02V Charging: 28.29%/hr Green
Rover Accuracy (m): 0.2745, SIV: 19
Rover Accuracy (m): 0.2648, SIV: 19
Batt (68%): Voltage: 4.02V Charging: 28.29%/hr Green
Rover Accuracy (m): 0.2580, SIV: 19
```

### Expected behavior
I don't know if it's a big deal, but it's strange, we should not see this type of message.

**Comment by Stefal** [comment]
> i was having a similar issue until i swapped from using the windows formatter to the offical sd one https://www.sdcard.org/downloads/formatter/

I have this issue without any micro-SD card inserted.

**Comment by nseidle** [comment]
On the Facet we don't have a hardware card detect, we have to use software: we send SPI commands every few seconds to detect if a user has hot-inserted an SD card.

What you are seeing are false-positives. The SPI interface is reporting that something responded, but then when we try to mount the card using the SdFat library, the library fails (because there is no card there). 

This should not affect the performance of the system. We should however try to suppress the frequency of the failure messages.
