### ISSUE TITLE
NTRIP Server restarted after going from Base to Rover

### ISSUE THREAD

**Issue by PaulZC** [sparkfun/SparkFun_RTK_Firmware#774]
When in Rover mode, it should not be possible to start the connections to the NTRIP Servers. But I see the server being started when in Rover mode - _after_ having been in Base.

Provide WiFi credentials.
Provide server details for one (or two) NTRIP servers.
Start the RTK in Temporary Base mode.
Allow the survey-in to complete. Firmware begins sending RTCM data to the servers.
Change to Rover mode.
The NTRIP server connections should be stopped, but I see them being periodically restarted - leading to WiFi badness when going into WiFi Config mode.

![image](https://github.com/sparkfun/SparkFun_RTK_Firmware/assets/5690545/77dfc6ba-f553-4fb8-a5e2-d4e92a844e1a)

**Comment by PaulZC** [comment]
After a _lot_ of digging and head-scratching, I eventually traced this to ```ntripServerRestart``` being called - instead of ```ntripServerStop```. I _believe_ calling ```ntripServerStop``` is the correct thing to do. ```ntripServerRestart``` actually turns the server on if the connection limit has not been reached... The same is true for ```ntripClientStop``` vs. ```ntripClientRestart```.

@nseidle @LeeLeahy2 : please review this commit and let me know if you agree with the solution : https://github.com/sparkfun/SparkFun_RTK_Firmware/commit/af73bf3e099c0fc887e93388aac789cea483ee4c

**Comment by nseidle** [comment]
Looks good to me.

**Comment by nseidle** [comment]
Fixed in [v4.1](https://github.com/sparkfun/SparkFun_RTK_Firmware/releases/tag/v4.1).
