### ISSUE TITLE
Continuos reboot on low bat

### ISSUE THREAD

**Issue by Eric-FR** [sparkfun/SparkFun_RTK_Firmware#83]
RTK Express with firmware 1.10.

When the express is running and the battery is reaching a low level, it stops... and start again with splash screen and, then, Rover screen and shut down again. It doesn't arrive at the normal screen nor create new files on the SD card.

I would like a proper shutdown.

**Comment by nseidle** [comment]
Fair. And should be easy to implement.

**Comment by nseidle** [comment]
I've set the cutoff at 5%. If a unit is below that at power on, it will power off. This should prevent rolling reboots.

Added to [v1.11 RC Mar 30](https://github.com/sparkfun/SparkFun_RTK_Firmware/releases/tag/v1.11). Please give it a try.
