### ISSUE TITLE
Don't shutdown on low bat when in charge

### ISSUE THREAD

**Issue by Eric-FR** [sparkfun/SparkFun_RTK_Firmware#88]
RTK Express with Firmware_v1_11-RCApr1

Battery was empty. I connect to my computer with USB to change settings. The serial monitor displayed:

> Batt (2%): Voltage: 3.83V Charging: 12.06%/hr Red
> Battery too low. Please charge. Shutting down...

Indeed, as device was in charge, there is no reason to switch it off.

**Comment by nseidle** [comment]
Ok - I think this is fixed in RCApr4.

**Comment by nseidle** [comment]
Fixed and rolled into v1.11 release. Please open new issue if you find anything else.
