### ISSUE TITLE
ECEF coordinates not saving over WiFi

### ISSUE THREAD

**Issue by bbrandau** [sparkfun/SparkFun_RTK_Firmware#97]
Unable to save configurations with base having a negative value for altitude in geodetic fixed base mode.  Also unable to save in ECEF mode with certain Z variables.  

Geodetic settings for my mountpoint:
39.50683985
-75.66554856
-4.198

ECEF Settings:
x: 1220012.70
y: -4774304.53
z: 4035886.32

**Comment by nseidle** [comment]
Hi @bbrandau - Thanks for reporting! Can you please let us know what firmware version you are using? Should be reported when you bring up the debug or system status menu. Once I know, we'll replicate.

**Comment by bbrandau** [comment]
1.11

**Comment by nseidle** [comment]
![image](https://user-images.githubusercontent.com/117102/163022886-2c07892e-d40f-4605-8565-4db57e6843bd.png)

Ah, I see, it's the range checking that needs to be modified. I fix that shortly

**Comment by nseidle** [comment]
Fixed in RCApr12 that you can get [here](https://github.com/sparkfun/SparkFun_RTK_Firmware/releases/tag/v1.11).

**Comment by bbrandau** [comment]
Thanks ... Looks like the Geodetic works, but the Z dimension for ECEF is still out of range.  It works well enough for what I need ... Thank you!!!

**Comment by nseidle** [comment]
My fault, I didn't take it low enough. 

Notes to my future self: Lowest location on earth: [dead sea](https://www.google.com/maps/place/31%C2%B032'00.0%22N+35%C2%B029'00.0%22E/@31.3462909,35.5283193), alt = -413m. [ECEF Converter]: 3316.212km.

I'm going to put the ECEF Z minimum at 3,300,000m and hope no one tries to setup a base station 16km below the dead sea.

**Comment by bbrandau** [comment]
Tested and works!!!!  Thanks!!!

**Comment by nseidle** [comment]
Just as a note - I was thinking in the completely wrong coordinate system here. ECEF X/Y/Z can be +/-[6,378,100](https://docs.wrld3d.com/unity/latest/docs/examples/ecef-coordinate-system). I'll get this fixed in v1.12.
